# -*- coding: utf-8 -*-
"""
TRENDSAPHIENS REHBERLERİ — kalıcı (evergreen) yazılar: her gün aranan sorunun "nasıl bakılır, nasıl
okunur" cevabı. Günlük sayfalar rakamı verir; rehber, rakamın nereden geldiğini ve nasıl doğrulanacağını.

Kural: tarih/kural bilgisi yalnızca kurumun kendi yayınına dayanır; kaynak listesi her yazının altında.
Rakam, hedef, tavsiye yok. Yazı /trend/<slug> olarak basılır; bölüm akışında kart olur.
"""

REHBERLER = [
    {
        "slug": "dolar-kac-tl-tcmb-kuru-banka-kuru-neden-farkli",
        "kat": "piyasa", "gorsel": "renk-masasi",
        "baslik": "Dolar kaç TL? TCMB kuru ile bankadaki kur neden farklı",
        "ozet": "Aynı gün üç ayrı dolar kuru görürsünüz: TCMB tablosu, bankanın gişesi, döviz bürosu. Hangisi 'gerçek', hangisi ne işe yarar, saat kaçta değişir — kaynağıyla.",
        "tarih": "2026-09-03",
        "bolumler": [
            ("Üç kur var, üçü de doğru",
             "\"Dolar kaç TL\" diye arayan kişi tek bir sayı bekler; oysa aynı anda geçerli üç ayrı kur vardır. Birincisi Türkiye Cumhuriyet Merkez Bankası'nın her iş günü yayımladığı gösterge kuru: resmî hesaplamalarda, gümrükte, sözleşmelerde \"TCMB döviz satış kuru\" diye anılan rakam budur. İkincisi bankanızın uyguladığı kur: alış ve satış arasında bankanın kendi makası vardır, gün içinde defalarca değişir. Üçüncüsü serbest piyasa, yani döviz bürolarının o anki fiyatı. Haber sitelerinin ekranında akan rakam çoğunlukla bankalararası piyasanın anlık verisidir; hiçbiri yanlış değildir, ama birbirinin yerine kullanılmaz."),
            ("TCMB tablosu saat kaçta çıkar, neyi gösterir",
             "TCMB gösterge kurlarını iş günlerinde 15:30'da yayımlar; tablo o günün tarihini taşır ve ertesi iş gününe kadar geçerli sayılır. Hafta sonu ve resmî tatilde yeni tablo çıkmaz; bu yüzden pazartesi sabahı gördüğünüz TCMB kuru cuma gününün tablosudur. Tabloda dört sütun vardır: döviz alış, döviz satış (hesaptan hesaba işlemler), efektif alış, efektif satış (nakit banknot). Bizim piyasa sayfamız bu tabloyu olduğu gibi alır; rakamın yanında tablonun tarihi ve bülten numarası yazar. Tablo henüz yayımlanmadıysa bir önceki günün tarihi görünür, biz yeni bir sayı uydurmayız."),
            ("Banka kuru neden farklı",
             "Banka, dövizi sizden alırken düşük, size satarken yüksek fiyat verir; aradaki fark bankanın gelirdir ve \"makas\" denir. Makas bankadan bankaya, hatta internet şubesi ile gişe arasında değişir. Gün içinde piyasa hareketlendikçe banka kurunu anlık günceller; TCMB tablosu ise günde bir kez çıkar. Bu yüzden akşam saatlerinde banka kuru ile TCMB kuru arasındaki fark büyüyebilir. Kredi kartı ile yurt dışı harcamada uygulanan kur da bankanın o günkü satış kurudur, TCMB tablosu değil."),
            ("Hangi durumda hangi kura bakılır",
             "Faturada, sözleşmede ya da resmî bir hesaplamada \"kur\" geçiyorsa genellikle TCMB döviz satış kuru kastedilir; metinde aksi yazmıyorsa bunu esas alın. Elinizdeki dövizi bozduracaksanız bankanızın ya da döviz bürosunun alış kuruna bakın. Haber okuyorsanız ekrandaki rakam anlık piyasa verisidir; gün sonunda TCMB tablosuyla birebir tutmayabilir. \"Dolar düştü mü çıktı mı\" sorusunun cevabı hangi kura, hangi saate baktığınıza göre değişir; bu yüzden karşılaştırırken aynı kaynağın aynı saatteki rakamlarını karşılaştırın."),
            ("Bu sitede nasıl gösteriyoruz",
             "Piyasalar bölümündeki günlük sayfa TCMB'nin XML tablosunu okur, kuru olduğu gibi yazar ve alınma saatini üstte gösterir. Altın için açık bir finans beslemesi kullanılır; kaynağın adı ve güncelleme saati satırın altındadır. Yorum, hedef ve tahmin yazılmaz. Rakamın neden değiştiğini merak ediyorsanız Gündem bölümündeki kaynaklı haberlere bakabilirsiniz; orada da rakam yalnızca haberde geçiyorsa yazılır."),
        ],
        "sss": [
            ("TCMB kuru hafta sonu değişir mi?", "Hayır. Tablo yalnızca iş günlerinde 15:30'da yayımlanır; hafta sonu ve tatilde son iş gününün tablosu geçerlidir."),
            ("Haberdeki dolar ile bankadaki dolar neden tutmuyor?", "Haber ekranı anlık bankalararası piyasayı gösterir; banka kendi makasını ekler. İkisi farklı şeyleri ölçer."),
            ("Sözleşmede 'TCMB kuru' yazıyorsa hangi sütun?", "Aksi belirtilmemişse döviz satış sütunu esas alınır; kesin olmak için sözleşme metnine bakın."),
        ],
        "kaynaklar": [("TCMB — Kurlar sayfası", "https://www.tcmb.gov.tr/kurlar/kurlar_tr.html"), ("TCMB — Günlük kur tablosu (XML)", "https://www.tcmb.gov.tr/kurlar/today.xml")],
    },
    {
        "slug": "gram-altin-nasil-hesaplanir-ons-dolar",
        "kat": "piyasa", "gorsel": "render-istasyonu",
        "baslik": "Gram altın kaç TL? Ons, dolar ve 31,1 ile hesabı",
        "ozet": "Gram altın fiyatı gökten inmez: ons fiyatı, dolar kuru ve bir sabit sayıdan hesaplanır. Kuyumcu fiyatı neden farklı, çeyrek neden gramın dörtte biri değil — kaynağıyla.",
        "tarih": "2026-09-03",
        "bolumler": [
            ("Formül tek satır",
             "Dünya piyasasında altın \"ons\" başına dolarla fiyatlanır. Bir ons 31,1035 gramdır. Gram altının TL karşılığı şöyle bulunur: ons fiyatı (dolar) çarpı dolar/TL kuru, bölü 31,1035. Yani gram altın iki şeye bağlıdır: dünyada altının dolar fiyatı ve Türkiye'de doların TL fiyatı. Ons sabit kalsa bile dolar yükselirse gram altın TL bazında yükselir; bu yüzden \"altın arttı\" haberinin bir kısmı aslında kur haberidir."),
            ("Kuyumcu fiyatı neden farklı",
             "Hesapladığınız rakam \"has altın\" değeridir. Kuyumcuda gördüğünüz gram fiyatı buna işçilik, kâr payı ve alış-satış makası ekler. Çeyrek, yarım ve tam altın da gramın katı değildir: çeyrek altın 1,75 gram civarında ve 22 ayardır, yani içinde saf altın oranı daha düşüktür; üstüne darphane ve kuyumcu farkı gelir. Bu yüzden çeyrek altın fiyatı gram altının dörtte birinden her zaman farklıdır."),
            ("Fiyat gün içinde neden değişir",
             "Ons fiyatı dünya piyasalarında 24 saat işlem görür; Asya, Avrupa ve Amerika seansları birbirini izler. Dolar/TL kuru da gün içinde hareket eder. İki değişkenin çarpımı olduğu için gram altın gün içinde sürekli oynar. Bu sitedeki piyasa sayfası fiyatı her sabah ve öğleden sonra bir kez alır; rakamın yanında beslemenin güncelleme saati yazar. Anlık işlem yapacaksanız kuyumcunuzun o anki fiyatını sorun."),
            ("Neye bakarak karar verilmez",
             "Bu sayfa ve günlük piyasa sayfaları bilgi verir, alım-satım önerisi vermez. \"Altın alınır mı\" sorusuna cevap vermeyiz; geçmiş fiyat geleceği göstermez. Bir rakamı paylaşırken kaynağını ve saatini de paylaşın; sosyal medyada dolaşan ekran görüntülerinin çoğu saati ve kaynağı belirsiz olduğu için yanıltır."),
        ],
        "sss": [
            ("Ons kaç gram?", "31,1035 gram. Kısaca 31,1 diye anılır; hassas hesapta tam değer kullanılır."),
            ("Çeyrek altın neden gramın dörtte biri değil?", "Çeyrek yaklaşık 1,75 gram ve 22 ayardır; üstüne işçilik ve makas gelir."),
            ("Bu sitedeki altın fiyatı anlık mı?", "Hayır; sabah ve öğleden sonra bir kez alınır, güncelleme saati satırın altında yazar."),
        ],
        "kaynaklar": [("TCMB — Kurlar", "https://www.tcmb.gov.tr/kurlar/kurlar_tr.html"), ("Borsa İstanbul — Kıymetli Madenler Piyasası", "https://www.borsaistanbul.com/")],
    },
    {
        "slug": "mac-hangi-kanalda-yayinci-nasil-bulunur",
        "kat": "spor", "gorsel": "set-isik",
        "baslik": "Maç hangi kanalda? Yayıncıyı yanılmadan bulmanın yolu",
        "ozet": "Süper Lig, millî maç, Avrupa kupaları ve voleybol: her birinin yayıncısı ayrı ve sezon içinde değişebiliyor. Doğru kanalı ve saati üç adımda, kaynağıyla doğrulama rehberi.",
        "tarih": "2026-09-03",
        "bolumler": [
            ("Yayın hakkı organizasyona göre değişir",
             "\"Maç hangi kanalda\" sorusunun tek cevabı yoktur, çünkü yayın hakları organizasyon bazında satılır. Süper Lig'in yayıncısı ile Türkiye Kupası'nın, millî takımın, Şampiyonlar Ligi'nin ve voleybol millî takımının yayıncısı ayrı ayrı belirlenir; aynı hafta sonu üç farklı platformda maç olabilir. Üstelik haklar sezon başında ya da ihaleyle sezon ortasında el değiştirebilir. Bu yüzden geçen sezon ezberlediğiniz kanal bu sezon geçerli olmayabilir."),
            ("Üç adımda doğrulama",
             "Birinci adım: organizasyonun kendi sitesi. Türkiye Futbol Federasyonu fikstür sayfasında maç saati ve çoğu zaman yayıncı bilgisi yer alır; UEFA ve TVF de kendi fikstürlerini yayımlar. İkinci adım: yayıncının kendi yayın akışı. Kanalın internet sitesindeki \"yayın akışı\" sayfası o günün programını saatiyle gösterir; haberdeki bilgiyle çelişiyorsa yayıncı esas alınır. Üçüncü adım: tarih. Haberdeki \"hangi kanalda\" bilgisi haberin tarihine aittir; ertelenen ya da saati değişen maçlar için en güncel duyuruya bakın."),
            ("Şifreli mi, şifresiz mi",
             "Bir maçın şifresiz yayınlanıp yayınlanmayacağı da organizasyona bağlıdır. Millî takım maçları çoğu zaman ulusal bir kanalda şifresiz verilir; lig maçları ise genellikle abonelik isteyen platformlardadır. \"Şifresiz mi\" sorusunun cevabı da yayıncının duyurusundadır; tahmin yazmayız. Yasal olmayan yayın adresleri için arama yapanlar için not: bu sayfalar hem güvenlik riski taşır hem de yayın kesilir; biz yalnızca resmî yayıncıyı yazarız."),
            ("Bu sitede spor ekranı nasıl çalışır",
             "Spor Ekranı bölümündeki günlük sayfa, o gün ve hafta sonu oynanacak maçlar için haber kaynaklarındaki \"hangi kanalda, saat kaçta\" maddelerini kaynağı ve tarihiyle listeler. Skor, yorum, tahmin ve bahis içeriği yoktur. Derbi ve millî maç günleri takvim kutusunda önceden görünür; sayfa maç günü sabah yenilenir. Yanlış bir yayıncı bilgisi görürseniz iletişim sayfasından yazın; düzeltir, düzelttiğimizi not ederiz."),
        ],
        "sss": [
            ("Millî maç hangi kanalda?", "Organizasyona göre değişir; TFF'nin fikstür sayfası ve yayıncının yayın akışı kesin kaynaktır. Günün maçları Spor Ekranı sayfasında kaynağıyla listelenir."),
            ("Derbi saat kaçta?", "Saat TFF fikstüründe yazar; hava, güvenlik ya da yayın nedeniyle değişebilir, maç günü tekrar bakın."),
            ("Kanal bilgisi neden haberden habere farklı?", "Haberler farklı tarihlerde yazılmıştır; en güncel tarihli duyuru ve yayıncının kendi sayfası esastır."),
        ],
        "kaynaklar": [("Türkiye Futbol Federasyonu", "https://www.tff.org/"), ("Türkiye Voleybol Federasyonu", "https://www.tvf.org.tr/"), ("UEFA", "https://www.uefa.com/")],
    },
    {
        "slug": "vizyona-giren-filmler-ne-zaman-aciklanir-nereden-bakilir",
        "kat": "ekran", "gorsel": "renk-masasi",
        "baslik": "Bu hafta vizyona giren filmler: ne zaman açıklanır, nereden bakılır",
        "ozet": "Türkiye'de filmler cuma günü vizyona girer; liste haftanın başında belli olur. Vizyon takvimi, gişe verisi ve platform yayınları için güvenilir kaynaklar ve okuma yöntemi.",
        "tarih": "2026-09-03",
        "bolumler": [
            ("Cuma günü kuralı",
             "Türkiye'de sinema haftası cuma başlar; yeni filmler cuma vizyona girer ve gişe haftası cuma-perşembe arasıdır. Dağıtımcılar vizyon tarihlerini aylar önceden duyurur, ancak liste son haftada değişebilir: bir film ertelenir, bir başkası eklenir. Bu yüzden \"bu hafta vizyona girenler\" haberi genellikle çarşamba-perşembe kesinleşir. Dizi & Film bölümündeki haftalık sayfa cuma sabahı çıkar; her film için dağıtımcı ya da yayıncı haberinin kaynağı ve tarihi yazılır."),
            ("Nereden bakılır",
             "Vizyon listesi için en sağlam kaynak dağıtımcıların kendi duyuruları ve gişe takip sitelerinin haftalık vizyon tablolarıdır; Türkiye'de gişe verisini derleyen Box Office Türkiye haftalık listeyi ve izleyici sayılarını yayımlar. Sinema zincirlerinin seans sayfaları da o hafta hangi filmin gerçekten gösterimde olduğunu gösterir: listede olup salonda olmayan film olabilir. Dizi ve platform yayınları için ise yayıncının kendi takvim sayfası esastır; \"yeni sezon ne zaman\" sorusunun kesin cevabı yalnızca oradadır."),
            ("Öneri nasıl yazılır, nasıl yazılmaz",
             "Bu bölümde film ve dizi önerisi beğeniyle değil ölçütle yazılır: tür, süre, yönetmen, nerede izlenir, kaynak. Puan vermeyiz; fragman ve afiş yayıncının telifidir, sayfaya alınmaz. Bir yapım şirketi olarak eklediğimiz katman şu: bir sahnenin nasıl çekildiğini, hangi ışıkla kurulduğunu arada yazarız, çünkü işimiz bu. İzleyici yorumu ve spoiler içermeyiz."),
            ("Haftalık düzen",
             "Cuma sabahı vizyon listesi, cuma öğlen haftanın dizi ve platform yayınları, hafta içi ise kaynaklı tekil haberler. Her sayfa tarihle arşivlenir; \"geçen hafta ne girmişti\" sorusunun cevabı arşivde kalır. Vizyon takvimi kutusu ana sayfada her hafta cuma için işaretlidir."),
        ],
        "sss": [
            ("Filmler neden cuma vizyona giriyor?", "Türkiye'de sinema haftası cuma başlar; gişe haftası cuma-perşembe sayılır."),
            ("Liste ne zaman kesinleşir?", "Genellikle çarşamba-perşembe; dağıtımcı erteleyebilir. Cuma sabahı sayfamız son hâli kaynağıyla verir."),
            ("Dizi yeni sezon tarihini nereden öğrenirim?", "Yayıncı kanalın ya da platformun kendi duyurusundan; haberler bu duyuruya bağlanır."),
        ],
        "kaynaklar": [("Box Office Türkiye — vizyon ve gişe", "https://boxofficeturkiye.com/")],
    },
    {
        "slug": "google-trends-bugun-en-cok-aranan-listesi-nasil-okunur",
        "kat": "aranan", "gorsel": "drone-safak",
        "baslik": "\"Bugün en çok aranan\" listesi nasıl okunur: Google Trends rehberi",
        "ozet": "Türkiye bugün ne aradı sayfamız Google Trends'ten beslenir. Hacim neden 'yaklaşık', sıralama kimin, bir başlık listeye nasıl girer, haber bağlantısı neden bazen yok — dürüst bir kullanım kılavuzu.",
        "tarih": "2026-09-03",
        "bolumler": [
            ("Liste kimin",
             "Google Trends, Google aramalarında kısa sürede sıçrama yapan konuları ülke bazında listeler. Türkiye listesi gün boyunca değişir; bir başlık sabah ilk sıradayken akşam listeden düşebilir. Bizim \"Türkiye bugün ne aradı\" sayfamız bu listeyi sabah ve öğleden sonra alır, sıralamayı değiştirmez. Listede olmayan bir konuyu eklemeyiz, listedeki bir konuyu da silmeyiz; yalnızca kaynağı belirsiz olanı yayımlamayız."),
            ("Hacim neden 'yaklaşık'",
             "Trends her başlık için \"100+\", \"1.000+\", \"5.000+\" gibi bir eşik verir; bu kesin arama sayısı değil, aşılan alt sınırdır. \"5.000+\" yazan bir başlık 5 bin de aranmış olabilir, 40 bin de. Bu yüzden sayfada \"yaklaşık\" yazar ve iki başlığı hacme göre kıyaslamak yanıltıcı olabilir. Kesin rakam isteyenler için Google'ın kendi arayüzü de kesin rakam vermez; bunu bilerek okumak gerekir."),
            ("Haber bağlantısı nereden gelir",
             "Google çoğu başlığın yanına o aramayla ilişkilendirdiği bir haberi ekler: başlık, kaynak ve adres. Biz bu bağlantıyı olduğu gibi gösteririz; haberi biz seçmedik, Google eşledi. Bazı başlıklara Google haber bağlamaz; o satırda \"Google bu başlığa haber bağlamadı\" yazar ve biz kendi kafamızdan bir haber eklemeyiz. Haberin kendisi kaynağın sitesindedir; biz metnini kopyalamayız."),
            ("Bölüm eşlemesi bizim, yanılabiliriz",
             "Her başlığı hangi bölümde okuyacağınızı (spor, piyasa, dizi-film, teknoloji…) anahtar kelimelere göre biz eşleriz. Bu eşleme bazen yanılır: bir oyuncu adı hem dizi hem magazin olabilir, bir şirket adı hem borsa hem teknoloji. Yanlış eşleme görürseniz yazın; düzeltiriz. Bu sayfanın amacı Google'ın listesini okunur, kaynaklı ve tarihli biçimde arşivlemektir; günün merakını yarın da bulabilmeniz için."),
        ],
        "sss": [
            ("Listeyi siz mi hazırlıyorsunuz?", "Hayır; Google Trends'in Türkiye listesidir. Biz sıralamaya dokunmayız, yalnız kaynak ve bölüm ekleriz."),
            ("'1.000+' ne demek?", "En az bin arama; üst sınır belirsiz. Kesin sayı değildir."),
            ("Dünkü listeyi görebilir miyim?", "Evet; her gün ayrı sayfa olarak arşivlenir, Bugün Aranan bölümünden tarihe göre açılır."),
        ],
        "kaynaklar": [("Google Trends — Türkiye", "https://trends.google.com/trending?geo=TR")],
    },
    {
        "slug": "enflasyon-verisi-ne-zaman-aciklanir-tuik-takvimi",
        "kat": "piyasa", "gorsel": "render-istasyonu",
        "baslik": "Enflasyon ne zaman açıklanır? TÜİK takvimi ve rakamı doğru okuma",
        "ozet": "Her ayın başında aynı soru aranıyor: enflasyon açıklandı mı, kaç çıktı, memur ve emekli zammına ne olur. Verinin saati, kaynağı ve 'enflasyon farkı' hesabının hangi kurala dayandığı — kaynaklı, tahminsiz.",
        "tarih": "2026-09-03",
        "bolumler": [
            ("Saat 10:00, ayın ilk günleri",
             "Tüketici fiyat endeksini Türkiye İstatistik Kurumu açıklar. Veri her ay TÜİK'in yıllık ulusal veri yayımlama takviminde ilan edilen günde, sabah 10:00'da yayımlanır; bu gün çoğunlukla ayın 3'üdür, hafta sonuna denk gelirse takvimde belirtilen ilk iş gününe kayar. Kesin gün için TÜİK'in yayımlama takvimine bakılır; biz takvim kutusunda ayın 3'ünü işaretleriz, TÜİK farklı bir gün ilan ettiyse o günü esas alırız. Açıklamadan önce dolaşan \"beklenti\" rakamları anket sonuçlarıdır, veri değildir."),
            ("Aylık mı, yıllık mı",
             "Açıklamada iki rakam öne çıkar: aylık değişim (bir önceki aya göre) ve yıllık değişim (geçen yılın aynı ayına göre). Haber başlıkları çoğu zaman yıllık rakamı verir; zam hesapları ise dönemsel toplama bakar. İki rakamı karıştırmamak için TÜİK'in haber bülteninde \"bir önceki aya göre\" ve \"bir önceki yılın aynı ayına göre\" ifadelerini birlikte okuyun. Bültenin sonunda madde gruplarına göre (gıda, ulaştırma, konut…) kırılım vardır; \"benim enflasyonum\" sorusunun cevabı o tabloda aranır."),
            ("Memur ve emekli zammı hesabı neye dayanır",
             "Memur maaş artışları toplu sözleşmeyle belirlenir; sözleşmede ayrıca \"enflasyon farkı\" maddesi vardır: altı aylık TÜFE artışı, sözleşmede o dönem için verilen zam oranını aşarsa aradaki fark maaşa yansır. Emekli aylıkları için de altı aylık TÜFE değişimi esas alınır. Bu yüzden ocak ve temmuz aylarından önceki veriler daha çok aranır. Hesap, dönemin son ayı açıklanınca kesinleşir; ondan önce yazılan her rakam tahmindir. Biz tahmin yazmayız; resmî oran Resmî Gazete'de ve ilgili bakanlık duyurusunda yayımlandığında kaynağıyla veririz."),
            ("Bu sitede nasıl gösteriyoruz",
             "Piyasalar bölümünde enflasyon günü takvim kutusunda görünür; veri açıklandığında günün gündem sayfasında TÜİK bülteninin kaynağıyla yer alır. Yorum ve tahmin yapmayız; rakam yalnızca TÜİK'in bülteninde geçiyorsa yazılır. Bu sayfa bilgi amaçlıdır, mali karar için resmî kaynaklara ve uzman görüşüne başvurulmalıdır."),
        ],
        "sss": [
            ("Enflasyon saat kaçta açıklanır?", "TÜİK verileri sabah 10:00'da yayımlar; gün, yıllık yayımlama takviminde ilan edilir."),
            ("Beklenti anketi ile gerçek veri aynı şey mi?", "Hayır. Anket tahmindir; veri TÜİK bültenidir."),
            ("Enflasyon farkı ne zaman belli olur?", "Altı aylık dönemin son ayı açıklandığında; öncesi tahmindir."),
        ],
        "kaynaklar": [("TÜİK — Veri portalı", "https://data.tuik.gov.tr/"), ("Resmî Gazete", "https://www.resmigazete.gov.tr/")],
    },
    {
        "slug": "yapay-zeka-ile-uretilmis-gorsel-nasil-anlasilir-etiket",
        "kat": "teknoloji", "gorsel": "render-istasyonu",
        "baslik": "Yapay zekâ ile üretilmiş görsel nasıl anlaşılır, ne zaman etiketlenir",
        "ozet": "Gördüğünüz görsel çekim mi, üretim mi? Beş pratik ipucu, üretim araçlarının bıraktığı izler ve reklamlarda etiket kuralı — kendi işimizde nasıl uyguladığımızla birlikte.",
        "tarih": "2026-09-03",
        "bolumler": [
            ("Neden artık anlaşılmıyor",
             "İki yıl önce yapay zekâ görsellerinde altı parmaklı eller, bozuk yazılar ve erimiş arka planlar vardı. Bugünkü görüntü modelleri bu hataları büyük ölçüde geride bıraktı; fotogerçekçi bir mimari kare ya da ürün fotoğrafı ilk bakışta çekimden ayırt edilmiyor. Bu, görselin \"sahte\" olduğu anlamına gelmez; üretim aracının değiştiği anlamına gelir. Sorun, görselin nereden geldiğinin söylenmemesidir."),
            ("Beş pratik ipucu",
             "Birincisi, yazı ve logolar: üretilmiş görsellerde tabela, etiket ve kitap sırtlarındaki yazılar hâlâ sık bozulur. İkincisi, tekrar eden doku: çim, kiremit, kaldırım taşı gibi desenler doğal olmayan biçimde tekrar edebilir. Üçüncüsü, ışık tutarlılığı: gölgelerin yönü ile ışık kaynağının yeri çelişebilir. Dördüncüsü, fiziksel mantık: merdiven hiçbir yere çıkmıyorsa, pencere sayısı iki cephede tutmuyorsa üretimdir. Beşincisi, meta veri: gerçek bir fotoğrafın dosyasında kamera modeli ve çekim ayarları vardır; üretilmiş görselde çoğunlukla yoktur ya da üretim aracının adı vardır. Hiçbiri tek başına kanıt değildir; birkaçı bir arada güçlü işarettir."),
            ("Etiket kuralı ve reklamlar",
             "Türkiye'de ticari reklamlarda yapay zekâ ile üretilmiş içeriğin belirtilmesi yönünde düzenleme yürürlüğe girdi; bu sitenin blogunda düzenlemenin ne getirdiği ayrıca yazılmıştır. Kural dışında da basit bir ilke var: bir görsel müşteriye ya da izleyiciye \"gerçek\" izlenimi veriyorsa ve değilse, bunu söylemek gerekir. Etiket görseli değersizleştirmez; güveni korur."),
            ("Kendi işimizde nasıl yapıyoruz",
             "Bu sitedeki yapay zekâ ile üretilmiş her kare küçük bir etiket taşır; 3D modelleme sayfasındaki \"final kare\" örneğinde blok model ile üretilmiş kare yan yana durur ve hangisinin nereden geldiği yazar. Müşteri teslimlerinde künye zorunludur: hangi kare çekim, hangi kare render, hangi kare üretim. Bu düzen hem düzenlemeyi karşılar hem de müşterinin kendi reklamında doğru etiketi kullanmasını sağlar."),
        ],
        "sss": [
            ("Meta veri yoksa görsel kesin yapay zekâ mı?", "Hayır; sosyal medya platformları meta veriyi siler. Diğer ipuçlarıyla birlikte değerlendirin."),
            ("Etiket görselin değerini düşürür mü?", "Deneyimimiz tersini söylüyor: müşteri ne aldığını bildiğinde güven artıyor."),
            ("Kendi reklamımda etiketi nereye koymalıyım?", "Görselin üzerinde ya da hemen yanında, okunur boyutta; ayrıntı için blogdaki düzenleme yazısına bakın."),
        ],
        "kaynaklar": [("Luna Yapım — Yapay zekâ reklamında etiketleme zorunluluğu", "https://lunayapim.com/blog/yapay-zeka-reklaminda-etiketleme-zorunlulugu"), ("Ticaret Bakanlığı", "https://www.ticaret.gov.tr/")],
    },
    {
        "slug": "isletme-sosyal-medya-haftalik-paylasim-takvimi",
        "kat": "sosyal-medya", "gorsel": "set-isik",
        "baslik": "İşletme hesabı için haftalık paylaşım takvimi: gerçekten sürdürülebilen düzen",
        "ozet": "Sosyal medyada düzenli görünmenin zor tarafı fikir değil, süreklilik. İki kişilik bir stüdyonun kendi hesapları için kullandığı haftalık düzen: içerik türleri, çekim günü, arşiv mantığı ve neyi ölçmeye değer.",
        "tarih": "2026-09-03",
        "bolumler": [
            ("Önce çekim günü, sonra takvim",
             "Çoğu işletme takvimi paylaşım günlerinden başlar ve üçüncü haftada tıkanır; çünkü her gün yeni malzeme üretmek mümkün değildir. Sürdürülebilen düzen tersten kurulur: haftada bir çekim günü, o günde beş-altı parça malzeme, hafta boyunca dağıtım. Bir ürünün dört farklı açısı, bir ustanın işini yaparken üç kısa planı, bir müşterinin bir cümlelik sözü — bir öğleden sonra bir haftayı doldurur."),
            ("Beş içerik türü, döner sırayla",
             "Birincisi \"iş\": bitmiş ürünü ya da hizmeti gösteren kare. İkincisi \"süreç\": nasıl yapıldığını gösteren kısa video; en çok izlenen tür genellikle budur. Üçüncüsü \"insan\": işi yapan kişi, konuşarak ya da çalışırken. Dördüncüsü \"bilgi\": müşterinin sık sorduğu bir sorunun kısa cevabı. Beşincisi \"kanıt\": müşteri sözü, önce-sonra, rakam yalnızca doğruysa. Bu beş tür haftaya dağılır; iki gün boş kalır, boş kalması sorun değildir."),
            ("Platform kuralı değil, format kuralı",
             "Aynı malzeme dikey kısa video, kare görsel ve yatay kapak olarak üç formatta hazırlanır; hangi platformun o hafta ne istediği önemli değildir, elinizde üçü de olur. Yazı platformlarında ise aynı malzemenin bir cümlelik hâli paylaşılır. Bu sitenin TrendSaphiens yayını da böyle çalışır: her sayfa bir başlık ve bir bağlantıyla X'e sırayla gider; metin kısa, rakam sayfada, kaynak sayfada."),
            ("Neyi ölçmeli",
             "Beğeni sayısı değil, iki şey: profil ziyaretinden mesaja ya da aramaya dönen kişi sayısı ve hangi içerik türünün bunu getirdiği. Platformların kendi istatistik ekranı bunu verir; ayrı araç gerekmez. Ayda bir bakılır, takvim ona göre düzeltilir. Algoritma söylentilerini takip etmek yerine kendi hesabınızın verisine bakmak daha az yorar ve daha doğru sonuç verir."),
        ],
        "sss": [
            ("Haftada kaç paylaşım yeterli?", "Sürdürebildiğiniz kadar; beş içerik türü ve bir çekim günüyle haftada 4-5 parça rahat çıkar."),
            ("Hangi platformla başlamalı?", "Müşterinizin olduğu tek platformla; format kuralı sayesinde diğerlerine sonra aynı malzemeyle geçilir."),
            ("Reklam vermeden büyür mü?", "Yavaş ama evet; süreç ve insan içerikleri en çok bunu sağlar. Rakam vaat etmiyoruz."),
        ],
        "kaynaklar": [("Luna Yapım — Sosyal medya yönetimi", "https://lunayapim.com/hizmetler/")],
    },
    {
        "slug": "sergi-konser-tiyatro-takvimi-nereden-takip-edilir",
        "kat": "sanat", "gorsel": "renk-masasi",
        "baslik": "Sergi, konser ve tiyatro takvimi nereden takip edilir",
        "ozet": "'Bu hafta sonu ne yapılır' sorusu için kaynak listesi: devlet kurumlarının takvimleri, belediye etkinlikleri, ücretsiz sergiler ve bilet sitelerini birlikte okuma yöntemi. Bursa ve İstanbul için ayrıca.",
        "tarih": "2026-09-03",
        "bolumler": [
            ("Dört kaynak türü",
             "Sanat takvimi tek yerde toplanmaz; dört kaynağı birlikte okumak gerekir. Birincisi kamu kurumları: Devlet Tiyatroları, Devlet Opera ve Balesi ve Cumhurbaşkanlığı Senfoni Orkestrası kendi sezon programlarını yayımlar, biletler çoğunlukla düşük fiyatlıdır. İkincisi belediyeler: kültür merkezlerinin aylık programları ve ücretsiz konserler belediyenin kültür sayfasında duyurulur. Üçüncüsü özel galeriler ve müzeler: sergi açılışları galerinin kendi sitesinde ve e-bülteninde. Dördüncüsü bilet platformları: ticari konserler ve festivaller için tarih ve fiyat orada kesinleşir."),
            ("Ücretsiz etkinlik nasıl bulunur",
             "Belediye konserleri, üniversite etkinlikleri, galeri açılışları ve kütüphane söyleşileri çoğunlukla ücretsizdir ve az duyurulur. Belediyenin kültür sayfasını ve şehirdeki galerilerin sosyal hesaplarını haftada bir taramak yeter. Sanat bölümündeki haftalık sayfamız ücretsiz etkinlikleri ayrıca işaretler; kaynağı ve tarihi olmayan etkinlik listeye girmez."),
            ("Bursa ve İstanbul",
             "Bursa'da Tayyare Kültür Merkezi, Merinos Atatürk Kongre ve Kültür Merkezi ile Bursa Devlet Tiyatrosu programları şehrin ana takvimini oluşturur; belediyenin festival dönemleri ayrıca yoğundur. İstanbul için sergi yoğunluğu Beyoğlu-Karaköy hattında ve büyük müzelerdedir; bienal yılında program ayrı takip edilir. Biz her iki şehri birlikte izler, diğer illerden kaynaklı duyuruları da alırız."),
            ("Bizim eklediğimiz katman",
             "Sahne ışığı, konser kaydı ve mekân çekimi bizim işimiz. Bu yüzden sanat bölümünde arada \"bir sergi nasıl çekilir, bir konser nasıl kaydedilir\" yazıları çıkar; etkinliğinizi belgelemek isterseniz nasıl yaptığımızı orada görürsünüz. Etkinliğinizin listeye girmesi için duyurunuzun adresini iletişim sayfasından göndermeniz yeter."),
        ],
        "sss": [
            ("Ücretsiz konser nereden öğrenilir?", "Belediyenin kültür sayfası ve üniversite duyuruları; haftalık sanat sayfamız kaynağıyla işaretler."),
            ("Devlet Tiyatrosu biletleri nereden alınır?", "Kurumun kendi bilet sistemi üzerinden; program sezon başında yayımlanır."),
            ("Etkinliğimi nasıl ekletirim?", "Kaynaklı ve tarihli duyuru adresini iletişim sayfasından gönderin."),
        ],
        "kaynaklar": [("Devlet Tiyatroları", "https://www.devtiyatro.gov.tr/"), ("Devlet Opera ve Balesi", "https://www.dobgm.gov.tr/"), ("Bursa Büyükşehir Belediyesi", "https://www.bursa.bel.tr/")],
    },
]


def hepsi():
    return list(REHBERLER)
