# -*- coding: utf-8 -*-
"""İl verisi — ek grup 1 (Adıyaman → Çorum)."""
EK = [
{"slug":"adiyaman","ad":"Adıyaman","ek":"'da","icin":"'a","ekip":"ortak","kademe":2,
 "ilceler":["Merkez","Kâhta","Besni","Gölbaşı","Samsat"],
 "insaat":"Adıyaman'da konut üretiminin gündemi deprem sonrası yeniden yapılanma; merkez ve Gölbaşı hattında yeni yerleşim alanları kuruluyor. Hak sahibine yeni yapının ne olacağını somut göstermek burada teknik bir tercih değil, güven meselesi.",
 "emlak":"Yeni teslim edilen konutlar ve ticari üniteler portföyün büyük kısmını oluşturuyor. Şehir dışında yaşayan hemşehri alıcı payı yüksek olduğu için mülkün uzaktan gezilebilir olması belirleyici.",
 "sanayi":"Tekstil ve konfeksiyon Adıyaman'ın en büyük istihdam kalemi; ayrıca petrol üretimi ve tarımsal işleme var. Konfeksiyon üreticileri için kumaş dokusunu ve üretim akışını gösteren video, fason müşteri bulmada doğrudan işe yarıyor.",
 "cografya":"Nemrut Dağı'nın dev heykelleri, Atatürk Baraj Gölü ve Cendere Köprüsü havadan çekimde ülke çapında tanınan kareler sunuyor.",
 "sektorler":["Tekstil ve konfeksiyon","Petrol ve enerji","Tarımsal işleme","İnşaat malzemesi"],
 "komsu":["gaziantep","kahramanmaras","malatya","sanliurfa"]},

{"slug":"afyonkarahisar","ad":"Afyonkarahisar","ek":"'da","icin":"'a","ekip":"ortak","kademe":2,
 "ilceler":["Merkez","Sandıklı","Dinar","Bolvadin","Sinanpaşa","İhsaniye"],
 "insaat":"Afyonkarahisar'da konut üretimi merkez çevresinde ve termal bölgede yoğunlaşıyor. Termal otel ve devremülk projeleri, yatırımcıya sunulurken tesisin ölçeğini ve kaynak avantajını görsel olarak anlatmak zorunda.",
 "emlak":"Termal devremülk ve otel yatırımı ilin en hareketli gayrimenkul kalemi; ayrıca şehir merkezinde klasik konut portföyü var. Devremülk satışında videolu tanıtım, uzaktaki alıcıyı ikna eden ana araç.",
 "sanayi":"Mermer ve doğal taş Afyonkarahisar'ı dünya pazarına bağlayan sektör; ayrıca et ürünleri, şeker ve tarım makineleri güçlü. Mermer damarının ve plaka boyutunun gerçekçi gösterildiği 3D anlatım, ihracat görüşmelerinde numune taşıma yükünü azaltıyor.",
 "cografya":"Afyon Kalesi'nin dik kayalığı, geniş ova ve Frig Vadisi'nin peribacaları havadan çekim için sıra dışı bir doku veriyor.",
 "sektorler":["Mermer ve doğal taş","Termal turizm","Et ve gıda ürünleri","Tarım makineleri","Şeker sanayi"],
 "komsu":["eskisehir","konya","denizli","kutahya"]},

{"slug":"agri","ad":"Ağrı","ek":"'da","icin":"'ya","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Doğubayazıt","Patnos","Diyadin","Eleşkirt"],
 "insaat":"Ağrı'da konut üretimi kamu yatırımları ve TOKİ projeleri ekseninde ilerliyor; özel sektörde ise merkez ve Patnos'ta orta ölçekli siteler var. Zorlu iklim nedeniyle yalıtım ve ısınma performansı satışın ilk konusu.",
 "emlak":"Sınır ticaretinin canlı olduğu Doğubayazıt'ta ticari mülk talebi konut talebinden daha hareketli. Turizm amaçlı pansiyon ve otel yatırımları için tanıtım videosu, İran ve Kafkas pazarına açılmada işe yarıyor.",
 "sanayi":"Hayvancılık, süt ürünleri ve sınır ticareti lojistiği ilin ekonomik omurgası. Süt işleme tesisleri için üretim hattı anlatımı, marka güveni kurmakta en hızlı yol.",
 "cografya":"Ağrı Dağı'nın 5137 metrelik zirvesi, İshak Paşa Sarayı ve Diyadin kanyonları Türkiye'nin en etkileyici havadan çekim manzaralarından bazıları.",
 "sektorler":["Hayvancılık ve süt ürünleri","Sınır ticareti ve lojistik","Turizm","Gıda işleme"],
 "komsu":["van","erzurum","igdir","mus"]},

{"slug":"aksaray","ad":"Aksaray","ek":"'da","icin":"'a","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Ortaköy","Eskil","Güzelyurt","Gülağaç"],
 "insaat":"Aksaray'da konut üretimi merkez çevresinde, üniversite ve OSB'nin çektiği nüfusa dönük ilerliyor. Kapadokya'ya yakın ilçelerde ise butik konaklama yatırımları artıyor.",
 "emlak":"Güzelyurt ve Ihlara çevresinde turizm amaçlı taş ev ve butik otel portföyü öne çıkıyor. Bu segmentte mülkün mimari dokusu ve vadiye bakışı ancak videoyla anlatılabiliyor.",
 "sanayi":"Kamyon ve ticari araç üretimi Aksaray'ın sanayi kimliğini belirliyor; ayrıca tarım makineleri ve gıda işleme güçlü. Ağır ticari araç üreticileri için kesit ve montaj animasyonu, bayi eğitiminde doğrudan kullanılıyor.",
 "cografya":"Ihlara Vadisi'nin 100 metrelik duvarları, Hasan Dağı ve Tuz Gölü kıyısı havadan çekimde birbirinden çok farklı üç ayrı dünya sunuyor.",
 "sektorler":["Ticari araç üretimi","Tarım makineleri","Gıda işleme","Turizm"],
 "komsu":["konya","nevsehir","nigde","ankara"]},

{"slug":"amasya","ad":"Amasya","ek":"'da","icin":"'ya","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Merzifon","Suluova","Taşova","Gümüşhacıköy"],
 "insaat":"Amasya'da merkez konut üretimi tarihi doku koruma kuralları nedeniyle sınırlı; asıl hareket Merzifon ve Suluova'da. Tarihi bölgede restorasyon projeleri, yapının önceki ve sonraki halini göstermeyi gerektiriyor.",
 "emlak":"Yeşilırmak kıyısındaki tarihi Yalıboyu evleri butik otel yatırımcısının ilgi alanında. Bu tip mülkte satışın kendisi mekânın atmosferini gösterebilmekten geçiyor.",
 "sanayi":"Şeker, süt ürünleri, tarım işleme ve Merzifon'da havacılık bakım faaliyetleri öne çıkıyor. Gıda üreticileri için hasattan pakete uzanan süreç videosu, zincir marketlere girişte fark yaratıyor.",
 "cografya":"Kral Kaya Mezarları'nın dik yamacı, Yeşilırmak boyunca dizilen Osmanlı evleri ve kale havadan çekimde tek karede toplanabiliyor.",
 "sektorler":["Gıda ve şeker","Süt ürünleri","Havacılık bakım","Tarım","Turizm"],
 "komsu":["samsun","tokat","corum","ordu"]},

{"slug":"ardahan","ad":"Ardahan","ek":"'da","icin":"'a","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Göle","Posof","Çıldır","Hanak"],
 "insaat":"Ardahan'da konut üretimi düşük hacimli; asıl yatırım turizm amaçlı bungalov ve dağ evi tarafında. Bu yapılarda arazi eğimi ve manzara açısı satışın tamamını belirliyor.",
 "emlak":"Çıldır Gölü çevresindeki araziler ve yayla evleri ilin en çok ilgi gören portföyü. Arazi satışında sınırların ve göle mesafenin havadan gösterilmesi ilk sorulan soruyu kapatıyor.",
 "sanayi":"Kaşar peyniri ve süt ürünleri Ardahan'ın markalaşmış üretimi; ayrıca bal ve organik hayvancılık var. Peynir üreticileri için üretim ve olgunlaştırma sürecini anlatan video, coğrafi işaret değerini görünür kılıyor.",
 "cografya":"Çıldır Gölü'nün kışın donan yüzeyi, Posof'un orman örtüsü ve geniş yaylalar Türkiye'de az bulunan bir görsel dil sunuyor.",
 "sektorler":["Süt ürünleri ve peynircilik","Hayvancılık","Arıcılık","Yayla turizmi"],
 "komsu":["kars","artvin","erzurum"]},

{"slug":"artvin","ad":"Artvin","ek":"'de","icin":"'e","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Hopa","Arhavi","Borçka","Yusufeli","Şavşat"],
 "insaat":"Artvin'de inşaatın en büyük belirleyicisi topografya: dik yamaçta hangi dairenin manzarayı gördüğü plan üzerinde anlaşılmıyor. Yusufeli'ndeki yeni yerleşim gibi taşınan yerleşimlerde 3D arazi modeli neredeyse zorunlu.",
 "emlak":"Yayla evi, bungalov ve dere kenarı arazi portföyün büyük kısmını oluşturuyor. Turizm amaçlı kiralanan mülklerde tanıtım videosu doluluğu doğrudan etkiliyor.",
 "sanayi":"Çay ve fındık işleme, bakır madenciliği ve Hopa üzerinden sınır lojistiği ilin ekonomik kolları. Çay üreticileri için hasat-işleme-paket süreci videosu, butik markalaşmada belirleyici.",
 "cografya":"Karagöl, Şavşat ormanları, Çoruh Vadisi ve dik yamaçlara kurulmuş köyler; Türkiye'nin havadan çekimde en dramatik illerinden biri.",
 "sektorler":["Çay işleme","Fındık","Madencilik","Sınır lojistiği","Doğa turizmi"],
 "komsu":["rize","ardahan","erzurum"]},

{"slug":"bartin","ad":"Bartın","ek":"'da","icin":"'a","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Amasra","Kurucaşile","Ulus"],
 "insaat":"Bartın'da konut üretimi merkez ve Amasra hattında, ağırlıklı olarak ikinci konut talebine dönük. Amasra'da yapılaşma kısıtları nedeniyle proje ölçekleri küçük ama birim değer yüksek.",
 "emlak":"Amasra'da deniz manzaralı butik daire ve pansiyon portföyü ilin en değerli kısmı. Alıcının çoğu Ankara ve İstanbul'dan geldiği için mülkün uzaktan gezilebilmesi satışı hızlandırıyor.",
 "sanayi":"Taş kömürü madenciliği, Kurucaşile'de geleneksel ahşap tekne imalatı ve orman ürünleri öne çıkıyor. Tekne imalatçıları için 3D ürün animasyonu, yurt dışı yat alıcısına ulaşmanın en pratik yolu.",
 "cografya":"Amasra'nın iki koyu, Kuşkayası Yol Anıtı ve Küre Dağları'nın denize inen ormanları havadan çekimde eşsiz bir kompozisyon veriyor.",
 "sektorler":["Ahşap tekne imalatı","Madencilik","Orman ürünleri","Turizm"],
 "komsu":["zonguldak","karabuk","kastamonu"]},

{"slug":"batman","ad":"Batman","ek":"'da","icin":"'a","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Kozluk","Beşiri","Sason","Gercüş"],
 "insaat":"Batman'da hızlı nüfus artışı konut talebini sürekli canlı tutuyor; merkez çevresinde çok katlı site projeleri yaygın. Genç nüfus oranı yüksek olduğundan projelerde sosyal donatı ve okul yakınlığı öne çıkarılıyor.",
 "emlak":"Şehir merkezinde konut, çevre yolunda ticari mülk ve depo portföyü hareketli. Ticari mülkte iç hacmin ve manevra alanının videoyla gösterilmesi yerinde gezme sayısını azaltıyor.",
 "sanayi":"Petrol rafinajı ve petrokimya Batman'ın sanayi kimliğini belirliyor; ayrıca tekstil ve gıda işleme var. Rafineri gibi gizlilik gerektiren tesislerde 3D animasyon, süreci hattı göstermeden anlatmanın tek yolu.",
 "cografya":"Hasankeyf'in taşınan anıtları, Batman Çayı ve Malabadi Köprüsü çevresi havadan çekimde tarihsel katmanı görünür kılıyor.",
 "sektorler":["Petrol ve petrokimya","Tekstil","Gıda işleme","İnşaat malzemesi"],
 "komsu":["mardin","siirt","diyarbakir","bitlis"]},

{"slug":"bayburt","ad":"Bayburt","ek":"'ta","icin":"'a","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Demirözü","Aydıntepe"],
 "insaat":"Türkiye'nin en küçük nüfuslu illerinden biri olan Bayburt'ta konut üretimi sınırlı ve büyük ölçüde yerel talebe dönük. Buna karşılık turizm amaçlı butik konaklama yatırımları son yıllarda artıyor.",
 "emlak":"Şehir merkezinde konut, kırsalda ise yayla evi ve arazi portföyü var. Şehir dışında yaşayan hemşehri alıcı ağırlıkta olduğu için ilanın uzaktan anlaşılabilir olması önemli.",
 "sanayi":"Taş işleme, süt ürünleri ve el sanatları öne çıkıyor. Bayburt taşı ile çalışan üreticiler için ürün ve uygulama animasyonu, mimar ve müteahhit müşterisine ulaşmada işe yarıyor.",
 "cografya":"Çoruh Vadisi, Bayburt Kalesi'nin şehre hâkim silueti ve geniş yaylalar havadan çekimde sade ama güçlü bir dil sunuyor.",
 "sektorler":["Taş işleme","Süt ürünleri","El sanatları","Yayla turizmi"],
 "komsu":["gumushane","erzurum","trabzon"]},

{"slug":"bilecik","ad":"Bilecik","ek":"'te","icin":"'e","ekip":"kendi","kademe":2,
 "ilceler":["Merkez","Bozüyük","Osmaneli","Söğüt","Pazaryeri","Gölpazarı"],
 "insaat":"Bilecik'te konut talebini büyük ölçüde Bozüyük'teki sanayi istihdamı belirliyor. Bursa ve Eskişehir arasında kalması nedeniyle yatırım amaçlı arsa hareketi de canlı.",
 "emlak":"Osmaneli ve Söğüt çevresinde bağ evi ve arazi portföyü, Bozüyük'te ise sanayi çalışanına dönük konut var. Arazi satışında sınır ve yol bağlantısının havadan gösterilmesi belirleyici.",
 "sanayi":"Seramik ve refrakter üretiminde Türkiye'nin önde gelen illerinden; ayrıca mermer ve makine imalatı güçlü. Seramik üreticileri için yüzey dokusunu ve uygulama sürecini gösteren animasyon, mimar ve bayi kanalında doğrudan satış aracı.",
 "cografya":"Söğüt'ün tarihi dokusu, Sakarya Nehri vadisi ve orman örtüsü; Bursa'ya yakınlığı sayesinde kendi ekibimizle aynı gün gidip dönebildiğimiz bir il.",
 "sektorler":["Seramik ve refrakter","Mermer","Makine imalatı","Kâğıt","Tarım"],
 "komsu":["bursa","eskisehir","sakarya","kutahya"]},

{"slug":"bingol","ad":"Bingöl","ek":"'de","icin":"'e","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Genç","Solhan","Karlıova","Adaklı"],
 "insaat":"Bingöl'de konut üretimi deprem yönetmeliğine uygun yenileme ekseninde ilerliyor; merkez çevresinde yeni siteler yükseliyor. Alıcının ilk sorusu yapı güvenliği olduğu için teknik anlatım satışın parçası.",
 "emlak":"Merkez konut portföyü ağırlıkta; kırsalda arazi ve yayla mülkü hareketli. Şehir dışı alıcı payı yüksek olduğu için videolu ilan ciddi avantaj sağlıyor.",
 "sanayi":"Bal üretimi Bingöl'ü ülke çapında tanıtan kalem; ayrıca hayvancılık ve gıda işleme var. Bal üreticileri için üretim ve hasat videosu, coğrafi işaretli ürünün taklitten ayrılmasını sağlıyor.",
 "cografya":"Yüzen Adalar, Kral Kızı Vadisi ve geniş yaylalar havadan çekimde az görülmüş kareler sunuyor.",
 "sektorler":["Arıcılık ve bal","Hayvancılık","Gıda işleme","Doğa turizmi"],
 "komsu":["elazig","mus","diyarbakir","erzincan"]},

{"slug":"bitlis","ad":"Bitlis","ek":"'te","icin":"'e","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Tatvan","Ahlat","Güroymak","Adilcevaz"],
 "insaat":"Bitlis'te konut üretimi Tatvan hattında yoğunlaşıyor; Van Gölü kıyısındaki projeler manzara üzerinden değer kazanıyor. Dik topografya nedeniyle hangi kattan gölün göründüğü ancak modelleme ile net gösterilebiliyor.",
 "emlak":"Göl manzaralı daireler ve Ahlat çevresindeki turizm amaçlı araziler portföyün öne çıkan kalemleri. Uzaktaki alıcı için sanal tur satışı kapatan adım oluyor.",
 "sanayi":"Tütün, ceviz ve gıda işleme; ayrıca Ahlat taşı ile taş işleme sektörü öne çıkıyor. Ahlat taşı üreticileri için uygulama ve doku animasyonu, mimarlık ofislerine ulaşmada etkili.",
 "cografya":"Nemrut Krater Gölü, Van Gölü kıyısı ve Ahlat Selçuklu Mezarlığı havadan çekimde Türkiye'nin en özgün üçlüsünden biri.",
 "sektorler":["Taş işleme (Ahlat taşı)","Gıda ve ceviz","Tütün","Turizm"],
 "komsu":["van","mus","batman","siirt"]},

{"slug":"bolu","ad":"Bolu","ek":"'da","icin":"'ya","ekip":"kendi","kademe":2,
 "ilceler":["Merkez","Gerede","Mudurnu","Göynük","Yeniçağa","Mengen"],
 "insaat":"Bolu'da konut üretiminin ana damarı ikinci konut ve dağ evi; Abant ve Kartalkaya çevresinde butik projeler sürekli talep görüyor. Alıcının neredeyse tamamı İstanbul ve Ankara'dan geldiği için proje uzaktan satılıyor.",
 "emlak":"Bungalov, dağ evi ve orman içi arazi portföyün merkezinde. Turizm amaçlı kiralanan bungalovlarda tanıtım videosu doluluk oranını doğrudan belirliyor.",
 "sanayi":"Orman ürünleri, kâğıt, gıda ve Gerede'de deri üretimi öne çıkıyor. Ayrıca Mengen aşçılık geleneğiyle gastronomi turizmi güçlü. Mobilya ve ahşap üreticileri için 3D varyant vitrini fabrika fotoğraf maliyetini düşürüyor.",
 "cografya":"Abant Gölü, Yedigöller, Kartalkaya'nın kar örtüsü ve D-100 boyunca uzanan orman; dört mevsim birbirinden farklı görüntü veren nadir illerden.",
 "sektorler":["Orman ürünleri ve kâğıt","Deri","Gıda ve gastronomi","Turizm ve konaklama"],
 "komsu":["duzce","sakarya","ankara","zonguldak"]},

{"slug":"burdur","ad":"Burdur","ek":"'da","icin":"'a","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Bucak","Gölhisar","Tefenni","Ağlasun"],
 "insaat":"Burdur'da konut üretimi ölçekli değil ama istikrarlı; merkez ve Bucak hattında orta büyüklükte siteler var. Göl manzaralı parseller son yıllarda yatırım amaçlı ilgi görüyor.",
 "emlak":"Burdur Gölü çevresindeki araziler ve şehir merkezindeki konut portföyü öne çıkıyor. Arazi ilanlarında topografya ve sulama altyapısının havadan gösterilmesi alıcıyı hızlandırıyor.",
 "sanayi":"Mermer ve doğal taş Burdur'un ihracat kalemi; ayrıca süt ürünleri, dokuma ve gül işleme var. Mermer ocaklarının ölçeğini ve plaka çeşitliliğini gösteren video, yurt dışı alıcısına numune öncesi güven veriyor.",
 "cografya":"Salda Gölü'nün beyaz kıyısı ve turkuaz suyu, Sagalassos antik kenti ve Burdur Gölü havadan çekimde ülke çapında tanınan kareler.",
 "sektorler":["Mermer ve doğal taş","Süt ürünleri","Dokuma","Gül ve tarım","Turizm"],
 "komsu":["antalya","isparta","denizli","mugla"]},
]
