# -*- coding: utf-8 -*-
"""İl verisi — ek grup 4 (Osmaniye → Zonguldak)."""
EK = [
{"slug":"osmaniye","ad":"Osmaniye","ek":"'de","icin":"'ye","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Kadirli","Düziçi","Bahçe","Toprakkale"],
 "insaat":"Osmaniye'de konut üretimi merkez ve Kadirli hattında; demir-çelik ve tarım istihdamı talebi besliyor. Yeni projelerde otoyol ve OSB'ye mesafe satış argümanının merkezinde.",
 "emlak":"Merkez konut, tarım arazisi ve otoyol kenarı ticari parsel portföyün kolları. Lojistik amaçlı depo ve arsa satışında havadan yol bağlantısı gösterimi belirleyici.",
 "sanayi":"Demir-çelik ve haddehane, yer fıstığı işleme, tarım ve gıda öne çıkıyor. Haddehane ve metal üreticileri için 3D süreç animasyonu, gizlilik gerektiren üretimi anlatmanın güvenli yolu.",
 "cografya":"Karatepe-Aslantaş açık hava müzesi, Aslantaş Barajı ve Amanos etekleri havadan çekimde tarih ve su bir arada.",
 "sektorler":["Demir-çelik ve haddehane","Yer fıstığı işleme","Tarım ve gıda","Lojistik"],
 "komsu":["adana","hatay","kahramanmaras","gaziantep"]},

{"slug":"rize","ad":"Rize","ek":"'de","icin":"'ye","ekip":"ortak","kademe":2,
 "ilceler":["Merkez","Çayeli","Ardeşen","Pazar","Fındıklı","Çamlıhemşin","İkizdere"],
 "insaat":"Rize'de dar kıyı şeridi ve dik yamaç, inşaatı hem zorlaştırıyor hem pahalılaştırıyor. Hangi dairenin denizi, hangisinin vadiyi gördüğü ancak arazi modeli üzerinde net gösterilebiliyor.",
 "emlak":"Deniz manzaralı daire, Ayder ve Çamlıhemşin'de bungalov, çay bahçesi arazisi portföyün kolları. Körfez ülkelerinden gelen alıcı ilgisi nedeniyle Arapça seslendirmeli tanıtım videosu talebi belirgin.",
 "sanayi":"Çay işleme Rize'nin kurucu sanayisi; ayrıca balıkçılık, gıda ve turizm hizmetleri var. Butik çay markaları için hasat-solma-kıvırma-paket süreci videosu, premium konumlandırmanın en güçlü aracı.",
 "cografya":"Ayder Yaylası, Fırtına Vadisi'nin kemer köprüleri, Zil Kale ve çay teraslarının yeşil dokusu havadan çekimde Türkiye'nin en tanınabilir yeşil kompozisyonu.",
 "sektorler":["Çay işleme","Balıkçılık","Yayla turizmi","Gıda","Orman ürünleri"],
 "komsu":["trabzon","artvin","erzurum"]},

{"slug":"siirt","ad":"Siirt","ek":"'te","icin":"'e","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Kurtalan","Pervari","Baykan","Eruh"],
 "insaat":"Siirt'te konut üretimi merkez çevresinde; genç nüfus ve üniversite talebi canlı tutuyor. Yeni projelerde iklime uygun gölgeleme ve serinlik çözümleri satış argümanı olabiliyor.",
 "emlak":"Merkez konut ve fıstıklık arazisi portföyün iki kolu. Fıstık bahçesi satışında sınır, sulama ve verim bilgisinin havadan gösterilmesi alıcıyı hızlandırıyor.",
 "sanayi":"Siirt fıstığı ve gıda işleme, battaniye dokumacılığı, bakır madenciliği ve petrol öne çıkıyor. Fıstık ve battaniye üreticileri için ürün doku animasyonu, coğrafi işaretli ürünü online pazarda ayırt edilir kılıyor.",
 "cografya":"Botan Vadisi'nin kanyonu, Pervari yaylaları ve Tillo'nun tarihi dokusu havadan çekimde derinlik ve ölçek veriyor.",
 "sektorler":["Fıstık ve gıda işleme","Battaniye dokumacılığı","Madencilik","Petrol","Hayvancılık"],
 "komsu":["batman","sirnak","bitlis","mardin"]},

{"slug":"sinop","ad":"Sinop","ek":"'ta","icin":"'a","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Boyabat","Gerze","Ayancık","Türkeli","Erfelek"],
 "insaat":"Sinop'ta konut üretimi ikinci konut talebine dönük ve ölçekli değil. Yarımada dokusu nedeniyle merkezde yeni yapı sınırlı; değer manzara ve konumda toplanıyor.",
 "emlak":"Deniz manzaralı daire, orman içi arazi ve merkezde tarihi konak portföyün kolları. Alıcının çoğu Ankara ve İstanbul'dan geldiği için uzaktan gezilebilir ilan belirleyici.",
 "sanayi":"Ahşap tekne ve kayık imalatı, balıkçılık, orman ürünleri ve Boyabat'ta pirinç üretimi öne çıkıyor. Tekne imalatçıları için 3D ürün animasyonu, yurt dışı alıcıya ulaşmanın en pratik yolu.",
 "cografya":"Sinop yarımadası ve tarihi cezaevi, Hamsilos Koyu, Erfelek Şelaleleri ve Ayancık ormanları havadan çekimde deniz-orman geçişini güçlü veriyor.",
 "sektorler":["Ahşap tekne imalatı","Balıkçılık","Orman ürünleri","Pirinç ve tarım","Turizm"],
 "komsu":["kastamonu","samsun","corum"]},

{"slug":"sivas","ad":"Sivas","ek":"'ta","icin":"'a","ekip":"ortak","kademe":2,
 "ilceler":["Merkez","Şarkışla","Suşehri","Zara","Gemerek","Divriği","Kangal"],
 "insaat":"Sivas'ta konut üretimi merkez çevresinde ve geniş parsellerde ilerliyor; üniversite ve demiryolu sanayisi istihdamı talebi besliyor. Termal bölgede ise konaklama yatırımı artıyor.",
 "emlak":"Merkez konut, termal çevresinde apart ve geniş tarım-mera arazisi portföyün kolları. Arazi ve mera satışında havadan sınır gösterimi standart hale geldi.",
 "sanayi":"Demir-çelik ve demiryolu araçları, çimento, halıcılık ve et-süt işleme öne çıkıyor. Demiryolu ve metal üreticileri için montaj ve kesit animasyonu, ihale ve bayi eğitiminde doğrudan kullanılıyor.",
 "cografya":"Divriği Ulu Camii'nin taş kapıları, Balıklı Kaplıca, Kızılırmak vadisi ve geniş step havadan çekimde UNESCO mirasıyla ölçeği bir arada veriyor.",
 "sektorler":["Demir-çelik ve demiryolu araçları","Çimento","Halıcılık","Et ve süt işleme","Termal turizm"],
 "komsu":["kayseri","malatya","erzincan","tokat"]},

{"slug":"sanliurfa","ad":"Şanlıurfa","ek":"'da","icin":"'ya","ekip":"ortak","kademe":2,
 "ilceler":["Haliliye","Eyyübiye","Karaköprü","Siverek","Viranşehir","Birecik","Suruç"],
 "insaat":"Şanlıurfa'da hızlı nüfus artışı konut talebini sürekli yukarı çekiyor; Karaköprü hattı ilin en hareketli yapı bölgesi. Sıcak iklim nedeniyle cephe gölgelemesi ve iç mekân serinliği satış argümanı haline geliyor.",
 "emlak":"Yeni gelişen bölgelerde konut, GAP sulama alanlarında tarım arazisi portföyün iki büyük kolu. Tarla satışında sulama kanalına mesafenin havadan gösterilmesi değeri doğrudan belirliyor.",
 "sanayi":"Tekstil, gıda işleme, un ve yağ sanayi ile tarımsal üretim öne çıkıyor. Tekstil ve gıda üreticileri için üretim hattı animasyonu, ihracat pazarında kapasiteyi anlatmanın en hızlı yolu.",
 "cografya":"Göbeklitepe, Balıklıgöl, Halfeti'nin sular altındaki minaresi ve Harran'ın kubbe evleri havadan çekimde dünya ölçeğinde tanınan kareler.",
 "sektorler":["Tekstil","Gıda ve yağ sanayi","Tarım ve GAP sulaması","Turizm","İnşaat malzemesi"],
 "komsu":["gaziantep","diyarbakir","mardin","adiyaman"]},

{"slug":"sirnak","ad":"Şırnak","ek":"'ta","icin":"'a","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Cizre","Silopi","İdil","Uludere"],
 "insaat":"Şırnak'ta konut üretimi merkez ve Cizre hattında; sınır ticaretinin beslediği nüfus talebi canlı tutuyor. Silopi'de lojistik tesis yatırımı konut kadar hareketli.",
 "emlak":"Cizre ve Silopi'de ticari mülk ve depo, merkezde konut portföyü var. Depo ve gümrük sahası satışında havadan ölçek ile yol bağlantısı gösterimi belirleyici.",
 "sanayi":"Kömür madenciliği, sınır ticareti lojistiği ve gıda işleme ilin ekonomik kolları. Lojistik firmaları için hizmet süreci animasyonu, gümrük ve taşıma akışını müşteriye anlatmanın en net yolu.",
 "cografya":"Cudi Dağı, Habur sınır kapısı çevresi ve Dicle vadisi havadan çekimde geniş ölçekli kareler veriyor.",
 "sektorler":["Madencilik (kömür)","Sınır ticareti ve lojistik","Gıda işleme","Hayvancılık"],
 "komsu":["mardin","siirt","hakkari"]},

{"slug":"tokat","ad":"Tokat","ek":"'ta","icin":"'a","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Turhal","Erbaa","Niksar","Zile","Reşadiye"],
 "insaat":"Tokat'ta konut üretimi merkez, Turhal ve Erbaa hattında; tarımsal sanayi istihdamı talebi besliyor. Tarihi merkezde ise konak restorasyonu ayrı bir alan.",
 "emlak":"Merkez konut, bağ-bahçe arazisi ve tarihi konak portföyün kolları. Bahçe ve tarla satışında havadan sınır ve sulama gösterimi alıcının ilk sorusunu kapatıyor.",
 "sanayi":"Şeker, konserve, süt ve et işleme, tekstil ve Tokat yazması öne çıkıyor. Konserve ve gıda üreticileri için hasattan kavanoza uzanan süreç videosu, zincir market tedarikinde güven kuruyor.",
 "cografya":"Ballıca Mağarası, Yeşilırmak vadisi, Tokat Kalesi ve Niksar'ın yeşil örtüsü havadan çekimde katmanlı bir doku veriyor.",
 "sektorler":["Gıda ve konserve","Şeker sanayi","Süt ve et işleme","Tekstil","Tarım"],
 "komsu":["amasya","sivas","ordu","yozgat"]},

{"slug":"tunceli","ad":"Tunceli","ek":"'de","icin":"'ye","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Pertek","Ovacık","Çemişgezek","Hozat"],
 "insaat":"Tunceli'de konut üretimi düşük hacimli; asıl yatırım doğa turizmine dönük butik konaklama tarafında. Baraj gölü kıyısındaki parseller son yıllarda ilgi görüyor.",
 "emlak":"Göl manzaralı arazi, merkez konut ve köy evi portföyün kolları. Şehir dışında yaşayan alıcı ağırlıkta olduğu için uzaktan gezilebilir ilan avantaj sağlıyor.",
 "sanayi":"Arıcılık ve bal, hayvancılık, su ürünleri ve doğa turizmi ilin ekonomik kolları. Bal üreticileri için yayla ve hasat videosu, yüksek rakım balının değerini anlatan en doğrudan materyal.",
 "cografya":"Munzur Vadisi Milli Parkı, Keban Baraj Gölü, Pertek Kalesi ve Ovacık yaylaları havadan çekimde Türkiye'nin en el değmemiş görüntülerinden.",
 "sektorler":["Arıcılık ve bal","Hayvancılık","Su ürünleri","Doğa turizmi"],
 "komsu":["elazig","erzincan","bingol"]},

{"slug":"usak","ad":"Uşak","ek":"'ta","icin":"'a","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Banaz","Eşme","Sivaslı","Ulubey"],
 "insaat":"Uşak'ta konut üretimi merkez çevresinde ve tekstil sanayinin çektiği istihdama dönük ilerliyor. Şehir ölçeği küçük olduğu için projelerde merkeze yürüme mesafesi güçlü bir satış argümanı.",
 "emlak":"Merkez konut ve OSB çevresinde sanayi parseli portföyün iki kolu. Fabrika binası satışında havadan ölçek ve yol bağlantısı gösterimi yatırımcı kararını hızlandırıyor.",
 "sanayi":"Battaniye ve tekstil geri dönüşümünde Türkiye'nin merkezi; ayrıca deri, seramik ve Eşme kilimi güçlü. Geri dönüşüm tesisleri için süreç animasyonu, sürdürülebilirlik anlatımını Avrupa müşterisine doğrudan veriyor.",
 "cografya":"Ulubey Kanyonu'nun uzun yarığı, Blaundos antik kenti ve geniş ova havadan çekimde beklenmedik bir derinlik sunuyor.",
 "sektorler":["Tekstil ve battaniye","Tekstil geri dönüşümü","Deri","Seramik","Kilim dokumacılığı"],
 "komsu":["manisa","denizli","afyonkarahisar","kutahya"]},

{"slug":"van","ad":"Van","ek":"'da","icin":"'a","ekip":"ortak","kademe":2,
 "ilceler":["İpekyolu","Tuşba","Edremit","Erciş","Gevaş","Muradiye"],
 "insaat":"Van'da konut üretimi Edremit ve Tuşba hattında; göl manzaralı projeler belirgin şekilde değer kazanıyor. Hangi kattan gölün göründüğü satışta doğrudan fiyata yansıdığı için manzara simülasyonu işlevsel.",
 "emlak":"Göl manzaralı daire, İran sınırına yakın ticari mülk ve tarım arazisi portföyün kolları. Sınır ticareti nedeniyle depo ve otel yatırımı hareketli.",
 "sanayi":"Otlu peynir ve süt ürünleri, hayvancılık, sınır ticareti lojistiği ve turizm hizmetleri öne çıkıyor. Peynir üreticileri için üretim ve olgunlaştırma videosu, coğrafi işaretli ürünü ulusal pazara taşıyor.",
 "cografya":"Van Gölü'nün turkuazı, Akdamar Adası'ndaki kilise, Van Kalesi ve Muradiye Şelalesi havadan çekimde denizsiz bir ilde deniz ölçeği veriyor.",
 "sektorler":["Süt ürünleri (otlu peynir)","Hayvancılık","Sınır ticareti","Turizm","Gıda işleme"],
 "komsu":["bitlis","agri","hakkari","mus"]},

{"slug":"yozgat","ad":"Yozgat","ek":"'ta","icin":"'a","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Sorgun","Akdağmadeni","Yerköy","Boğazlıyan","Sarıkaya"],
 "insaat":"Yozgat'ta konut üretimi merkez ve Sorgun hattında; üniversite ve termal yatırımlar talebi besliyor. Geniş parseller sayesinde projelerde bahçe ve otopark öne çıkarılabiliyor.",
 "emlak":"Merkez konut, termal bölgede apart ve geniş tarım arazisi portföyün kolları. Tarla satışında havadan parsel ve yol gösterimi alıcıyı hızlandırıyor.",
 "sanayi":"Tarımsal işleme, un ve yem sanayi, mermer ve termal turizm öne çıkıyor. Un ve yem üreticileri için üretim hattı videosu, bayi ve toptancı ağına kapasiteyi anlatmanın yolu.",
 "cografya":"Çamlık Milli Parkı'nın karaçam ormanı, Sarıkaya Roma hamamı ve geniş step havadan çekimde sakin, geniş açı kareler veriyor.",
 "sektorler":["Tarımsal işleme","Un ve yem sanayi","Mermer","Termal turizm","Hayvancılık"],
 "komsu":["kirikkale","sivas","corum","kirsehir"]},

{"slug":"zonguldak","ad":"Zonguldak","ek":"'ta","icin":"'a","ekip":"ortak","kademe":2,
 "ilceler":["Merkez","Ereğli","Çaycuma","Devrek","Alaplı","Kdz. Ereğli"],
 "insaat":"Zonguldak'ta konut üretimi dik topografya nedeniyle dar alanlarda ve dikey ilerliyor; Ereğli hattı demir-çelik istihdamıyla en hareketli bölge. Deniz görüşünün kat bazında değişmesi manzara simülasyonunu işlevli kılıyor.",
 "emlak":"Ereğli'de sanayi çalışanına dönük konut, Alaplı ve kıyı hattında yazlık portföy var. Şehir dışından gelen alıcı için uzaktan gezilebilir ilan belirleyici.",
 "sanayi":"Taş kömürü madenciliği ve demir-çelik Zonguldak'ın kurucu sanayileri; ayrıca Devrek bastonu ve orman ürünleri var. Ağır sanayi tesislerinde 3D süreç animasyonu, gizlilik ve iş güvenliği nedeniyle çekim yapılamayan hatları anlatmanın tek yolu.",
 "cografya":"Gökgöl Mağarası, Filyos Vadisi, Kdz. Ereğli limanı ve ormanla denizin buluştuğu dik kıyı havadan çekimde sanayi ile doğayı bir arada veriyor.",
 "sektorler":["Taş kömürü madenciliği","Demir-çelik","Orman ürünleri","Liman ve lojistik","Baston ve el sanatları"],
 "komsu":["bartin","duzce","karabuk","bolu"]},
]
