# -*- coding: utf-8 -*-
"""İl verisi — ek grup 3 (Kahramanmaraş → Ordu)."""
EK = [
{"slug":"kahramanmaras","ad":"Kahramanmaraş","ek":"'ta","icin":"'a","ekip":"ortak","kademe":2,
 "ilceler":["Onikişubat","Dulkadiroğlu","Elbistan","Afşin","Türkoğlu","Pazarcık"],
 "insaat":"Kahramanmaraş'ta inşaatın gündemi deprem sonrası yeniden yapılanma; Onikişubat ve Dulkadiroğlu'nda büyük ölçekli yeni yerleşimler kuruluyor. Alıcının ilk sorusu zemin ve yapı sistemi olduğu için teknik anlatım satışın merkezinde.",
 "emlak":"Yeni teslim konutlar ve OSB çevresindeki sanayi parselleri portföyün iki ana kolu. Şehir dışına taşınmış alıcı payı yüksek olduğu için mülkün uzaktan gezilebilmesi belirleyici.",
 "sanayi":"Tekstil ve iplik Kahramanmaraş'ı ülke ölçeğinde tanıtan sektör; ayrıca dondurma ve gıda, metal ve çelik eşya güçlü. İplik ve kumaş üreticileri için doku ve üretim hattı animasyonu, fuar ve ihracat görüşmelerinin ana materyali.",
 "cografya":"Ahır Dağı'nın şehre bakan yamacı, Ceyhan Nehri ve Yedikuyular'ın kar örtüsü havadan çekimde geniş açı planlar veriyor.",
 "sektorler":["Tekstil ve iplik","Gıda (dondurma, biber)","Metal ve çelik eşya","Enerji","Tarım"],
 "komsu":["gaziantep","adana","osmaniye","adiyaman"]},

{"slug":"karabuk","ad":"Karabük","ek":"'te","icin":"'e","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Safranbolu","Yenice","Eskipazar","Eflani"],
 "insaat":"Karabük'te konut talebini demir-çelik istihdamı ve üniversite nüfusu belirliyor. Safranbolu'da ise yeni yapı yerine tarihi konak restorasyonu ana faaliyet ve bu, önce-sonra anlatımını değerli kılıyor.",
 "emlak":"Safranbolu konakları butik otel yatırımcısının hedefinde; merkezde ise klasik konut portföyü var. Konak satışında mekânın atmosferini gösterebilmek satışın kendisi.",
 "sanayi":"Demir-çelik Karabük'ün kurucu sanayisi; ayrıca orman ürünleri ve yan sanayi güçlü. Ağır sanayi tesislerinde havadan ölçek çekimi ve 3D süreç animasyonu, ihale ve yatırımcı sunumunda kullanılıyor.",
 "cografya":"Safranbolu'nun UNESCO listesindeki çatı denizi, Yenice ormanları ve Tokatlı Kanyonu havadan çekimde nadir bir doku sunuyor.",
 "sektorler":["Demir-çelik","Orman ürünleri","Turizm ve konaklama","Metal yan sanayi"],
 "komsu":["bartin","kastamonu","cankiri","zonguldak"]},

{"slug":"karaman","ad":"Karaman","ek":"'da","icin":"'a","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Ermenek","Ayrancı","Kazımkarabekir","Sarıveliler"],
 "insaat":"Karaman'da konut üretimi merkez çevresinde, gıda sanayinin çektiği istihdama dönük ilerliyor. Geniş parseller sayesinde projelerde iç peyzaj ve otopark satış argümanı olabiliyor.",
 "emlak":"Merkez konut ve tarım arazisi portföyün iki kolu; Ermenek'te ise turizm amaçlı arazi ilgi görüyor. Elma bahçesi ve tarla satışında havadan sınır gösterimi standart hale geldi.",
 "sanayi":"Bisküvi ve gofret üretiminde Türkiye'nin merkezi; ayrıca un, süt ürünleri ve elma işleme güçlü. Gıda üreticileri için üretim hattı ve hijyen süreci animasyonu, zincir market ve ihracat denetimlerinde anlatımı kısaltıyor.",
 "cografya":"Taşkale'nin kaya ambarları, Ermenek Barajı'nın derin vadisi ve geniş ova havadan çekimde beklenmedik bir çeşitlilik veriyor.",
 "sektorler":["Bisküvi ve gıda","Un ve değirmen","Süt ürünleri","Elma ve tarım","Madencilik"],
 "komsu":["konya","mersin","antalya"]},

{"slug":"kars","ad":"Kars","ek":"'ta","icin":"'a","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Sarıkamış","Kağızman","Selim","Digor","Susuz"],
 "insaat":"Kars'ta konut üretimi merkez çevresinde sınırlı; asıl yatırım Sarıkamış'ta kış turizmine dönük otel ve apart projelerinde. Sert iklim nedeniyle yalıtım performansı proje anlatımının ilk maddesi.",
 "emlak":"Sarıkamış'ta sezonluk kiralanan apart ve otel, merkezde ise tarihi Baltık mimarisi taş binalar portföyün ilgi çeken kısmı. Turizm mülkünde tanıtım videosu doluluk oranını doğrudan belirliyor.",
 "sanayi":"Kaşar peyniri ve süt ürünleri Kars'ın markası; ayrıca bal, hayvancılık ve turizm hizmetleri var. Peynir üreticileri için mera-üretim-olgunlaştırma videosu, coğrafi işaretin değerini anlatan en güçlü materyal.",
 "cografya":"Ani Harabeleri'nin surları, Sarıkamış'ın sarıçam ormanı, Kars Kalesi ve Çıldır yolu havadan çekimde tarih ve karı bir arada veriyor.",
 "sektorler":["Süt ürünleri ve kaşar","Arıcılık ve bal","Hayvancılık","Kış ve kültür turizmi"],
 "komsu":["ardahan","igdir","erzurum","agri"]},

{"slug":"kastamonu","ad":"Kastamonu","ek":"'da","icin":"'ya","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Tosya","Taşköprü","İnebolu","Cide","Araç","Devrekani"],
 "insaat":"Kastamonu'da konut üretimi merkez ve Tosya hattında; tarihi konak restorasyonu ise ayrı ve büyüyen bir alan. Kıyı ilçelerinde ikinci konut talebi son yıllarda arttı.",
 "emlak":"Merkezde tarihi konak, kıyıda yazlık, kırsalda orman içi arazi portföyün üç kolu. Şehir dışından gelen alıcı ağırlıkta olduğu için videolu ilan gezme sayısını azaltıyor.",
 "sanayi":"Orman ürünleri ve kereste, Taşköprü sarımsağı, pirinç ve gıda işleme öne çıkıyor. Sarımsak ve gıda üreticileri için hasat-kurutma-paket videosu, coğrafi işaretli ürünü taklitten ayırıyor.",
 "cografya":"Küre Dağları'nın kanyonları, Ilgaz'ın kar örtüsü, Cide sahili ve Kastamonu'nun ahşap konakları havadan çekimde geniş bir yelpaze sunuyor.",
 "sektorler":["Orman ürünleri ve kereste","Gıda (sarımsak, pirinç)","Turizm","Mobilya"],
 "komsu":["sinop","bartin","cankiri","karabuk"]},

{"slug":"kilis","ad":"Kilis","ek":"'te","icin":"'e","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Musabeyli","Elbeyli","Polateli"],
 "insaat":"Kilis'te konut üretimi merkez çevresinde ve sınırlı hacimde; hızlı nüfus değişimi talebi canlı tutuyor. Yeni projelerde okul ve sağlık tesisine mesafe satış argümanının merkezinde.",
 "emlak":"Konut portföyünün yanında sınır ticareti nedeniyle depo ve ticari alan talebi hareketli. Ticari mülkte hacim ve yükleme alanının videoyla gösterilmesi yerinde gezmeyi azaltıyor.",
 "sanayi":"Zeytinyağı, bağcılık, sabun ve gıda işleme Kilis'in üretim kolları; sınır ticareti lojistiği de güçlü. Zeytinyağı üreticileri için hasat ve sıkım videosu, butik markalaşmada belirleyici.",
 "cografya":"Ravanda Kalesi, zeytinlikler ve sınır boyunca uzanan ova havadan çekimde sade ama tanınabilir bir doku veriyor.",
 "sektorler":["Zeytinyağı","Bağcılık","Sabun ve gıda","Sınır ticareti"],
 "komsu":["gaziantep","hatay"]},

{"slug":"kirikkale","ad":"Kırıkkale","ek":"'de","icin":"'ye","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Yahşihan","Keskin","Delice","Bahşılı"],
 "insaat":"Kırıkkale'de konut talebini savunma sanayi ve rafineri istihdamı ile üniversite nüfusu belirliyor. Ankara'ya yakınlık, yatırım amaçlı konut alımını canlı tutuyor.",
 "emlak":"Merkez konut ve Ankara yolu üzerindeki ticari parseller portföyün ana kalemleri. Lojistik amaçlı depo satışında havadan yol bağlantısı gösterimi belirleyici.",
 "sanayi":"Savunma sanayi, petrol rafinajı ve makine imalatı Kırıkkale'nin sanayi kimliği. Savunma ve makine üreticileri için kesit ve montaj animasyonu, gizlilik sınırları içinde ürünü anlatmanın yolu.",
 "cografya":"Kızılırmak'ın şehri çevreleyen kıvrımları ve geniş step havadan çekimde temiz geometrik kompozisyonlar veriyor.",
 "sektorler":["Savunma sanayi","Petrol rafinajı","Makine imalatı","Metal işleme"],
 "komsu":["ankara","kirsehir","yozgat","corum"]},

{"slug":"kirklareli","ad":"Kırklareli","ek":"'nde","icin":"'ne","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Lüleburgaz","Babaeski","Vize","Demirköy","Kıyıköy"],
 "insaat":"Kırklareli'nde konut üretimi Lüleburgaz'daki sanayi istihdamına dönük ilerliyor; Kıyıköy ve Demirköy'de ise doğa turizmi amaçlı butik yatırım artıyor. İstanbul'a yakınlık arsa hareketini canlı tutuyor.",
 "emlak":"Bağ evi, orman içi arazi ve sanayi çevresinde konut portföyün kolları. Arazi ilanlarında sınır ve yol bağlantısının havadan gösterilmesi standart hale geldi.",
 "sanayi":"Cam, tekstil, gıda ve bağcılık-şarapçılık Kırklareli'nin üretim kolları; Trakya'nın en yoğun sanayi hatlarından biri. Cam ve tekstil üreticileri için ürün doku animasyonu, ihracat sunumlarında numune ihtiyacını azaltıyor.",
 "cografya":"Istranca ormanları, Kıyıköy'ün Karadeniz kıyısı, bağlar ve Dupnisa Mağarası havadan çekimde Trakya'nın az bilinen yüzünü gösteriyor.",
 "sektorler":["Cam","Tekstil","Gıda ve bağcılık","Tarım","Doğa turizmi"],
 "komsu":["tekirdag","edirne","istanbul"]},

{"slug":"kirsehir","ad":"Kırşehir","ek":"'de","icin":"'e","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Kaman","Mucur","Çiçekdağı","Akpınar"],
 "insaat":"Kırşehir'de konut üretimi merkez ve üniversite çevresinde yoğunlaşıyor; termal bölgede ise konaklama yatırımı var. Geniş parseller projelerde peyzaj ve otopark avantajı yaratıyor.",
 "emlak":"Merkez konut, termal çevresinde apart ve kırsalda tarım arazisi portföyün kolları. Ceviz bahçesi ve tarla satışında havadan parsel gösterimi alıcıyı hızlandırıyor.",
 "sanayi":"Ceviz üretimi, tarımsal işleme, mermer ve gıda öne çıkıyor. Ceviz ve gıda üreticileri için hasat-işleme videosu, market ve ihracat kanalında izlenebilirlik anlatıyor.",
 "cografya":"Cacabey Medresesi'nin taş işçiliği, Kaman'ın ceviz bahçeleri ve geniş step havadan çekimde sakin bir kompozisyon veriyor.",
 "sektorler":["Ceviz ve tarımsal işleme","Mermer","Gıda","Termal turizm"],
 "komsu":["kirikkale","nevsehir","yozgat","aksaray"]},

{"slug":"kutahya","ad":"Kütahya","ek":"'da","icin":"'ya","ekip":"kendi","kademe":2,
 "ilceler":["Merkez","Tavşanlı","Simav","Gediz","Emet","Domaniç"],
 "insaat":"Kütahya'da konut üretimi merkez ve Tavşanlı hattında, madencilik ve seramik istihdamına dönük ilerliyor. Simav'da ise termal kaynak çevresinde konaklama yatırımı var.",
 "emlak":"Merkez konut, termal bölgede apart ve kırsalda arazi portföyün kolları. Termal mülkte kaynak avantajının anlatılması satışın belirleyicisi.",
 "sanayi":"Seramik ve porselen Kütahya'nın dünya çapındaki kimliği; ayrıca bor madenciliği, çini ve şeker sanayi güçlü. Seramik ve çini üreticileri için desen ve uygulama animasyonu, ihracat ve mimar kanalında doğrudan satış aracı.",
 "cografya":"Kütahya Kalesi, Frig Vadisi'nin kaya oyma anıtları, Murat Dağı ve Simav ovası; Bursa'dan aynı gün ulaşılabilen bir il.",
 "sektorler":["Seramik ve porselen","Çini","Bor madenciliği","Şeker sanayi","Termal turizm"],
 "komsu":["bursa","eskisehir","afyonkarahisar","manisa"]},

{"slug":"malatya","ad":"Malatya","ek":"'da","icin":"'ya","ekip":"ortak","kademe":2,
 "ilceler":["Battalgazi","Yeşilyurt","Doğanşehir","Akçadağ","Darende","Hekimhan"],
 "insaat":"Malatya'da inşaatın gündemi deprem sonrası yeniden yapılanma; Yeşilyurt ve Battalgazi'de büyük ölçekli yeni yerleşimler kuruluyor. Yapı güvenliği ve teslim takvimi, satış anlatımının iki temel maddesi.",
 "emlak":"Yeni teslim konutlar ve kayısı bahçesi arazileri portföyün iki kolu. Şehir dışına taşınmış alıcı payı yüksek olduğu için uzaktan gezilebilir ilan zorunlu hale geldi.",
 "sanayi":"Kayısı işleme Malatya'yı dünya pazarına bağlayan sektör; ayrıca tekstil, gıda ve madencilik var. Kayısı ihracatçıları için bahçeden pakete uzanan süreç videosu, gıda güvenliği anlatımını tek karede veriyor.",
 "cografya":"Levent Vadisi'nin kanyonu, Nemrut'a uzanan yollar, kayısı bahçeleri ve Battalgazi'nin tarihi dokusu havadan çekimde güçlü açılışlar sunuyor.",
 "sektorler":["Kayısı ve gıda işleme","Tekstil","Madencilik","Tarım","İnşaat malzemesi"],
 "komsu":["elazig","adiyaman","kahramanmaras","sivas"]},

{"slug":"mardin","ad":"Mardin","ek":"'de","icin":"'e","ekip":"ortak","kademe":2,
 "ilceler":["Artuklu","Midyat","Kızıltepe","Nusaybin","Dargeçit","Savur"],
 "insaat":"Mardin'de yeni yapılaşma tarihi siluetin korunması nedeniyle Yenişehir tarafına kaydırılmış; eski şehirde ise taş ev restorasyonu ana faaliyet. Restorasyon projelerinde önce-sonra anlatımı hem ruhsat hem satış için değerli.",
 "emlak":"Midyat ve Artuklu'da taş konak, Kızıltepe'de tarım arazisi, Nusaybin'de ticari mülk portföyün kolları. Butik otel yatırımcısı için mekânın atmosferini gösterebilmek satışın kendisi.",
 "sanayi":"Taş işlemeciliği, telkâri gümüş işçiliği, tarımsal işleme ve sınır ticareti öne çıkıyor. Telkâri ustaları için ürün 3D vitrini ve makro animasyon, küçük ürünü online pazarda satılabilir kılıyor.",
 "cografya":"Mezopotamya ovasına bakan taş şehir silueti, Deyrulzafaran Manastırı ve Dara antik kenti havadan çekimde Türkiye'nin en tanınabilir kompozisyonlarından biri.",
 "sektorler":["Taş işlemeciliği","Telkâri ve gümüş","Tarımsal işleme","Sınır ticareti","Turizm"],
 "komsu":["diyarbakir","batman","sanliurfa","sirnak"]},

{"slug":"mus","ad":"Muş","ek":"'ta","icin":"'a","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Bulanık","Malazgirt","Varto","Korkut"],
 "insaat":"Muş'ta konut üretimi merkez çevresinde ve kamu yatırımları ekseninde ilerliyor. Geniş ova sayesinde yatay yerleşim mümkün; projelerde bahçe ve otopark satış argümanı olabiliyor.",
 "emlak":"Merkez konut ve ova tarım arazisi portföyün iki kolu. Tarla ve mera satışında sınır ile sulama altyapısının havadan gösterilmesi alıcının ilk sorusunu kapatıyor.",
 "sanayi":"Hayvancılık, süt ürünleri, şeker pancarı ve tarımsal işleme ilin ekonomik kolları. Süt işleyicileri için üretim hattı videosu, bölgesel marka güveni kurmakta en hızlı yol.",
 "cografya":"Muş ovasının uçsuz düzlüğü, Malazgirt ovası ve ilkbaharda lale örtüsü havadan çekimde ölçek duygusu güçlü kareler veriyor.",
 "sektorler":["Hayvancılık ve süt ürünleri","Şeker pancarı","Tarımsal işleme","Gıda"],
 "komsu":["bitlis","bingol","agri","van"]},

{"slug":"nevsehir","ad":"Nevşehir","ek":"'de","icin":"'e","ekip":"ortak","kademe":2,
 "ilceler":["Merkez","Ürgüp","Avanos","Göreme","Uçhisar","Gülşehir","Derinkuyu"],
 "insaat":"Nevşehir'de yapılaşma koruma bölgesi kuralları nedeniyle sınırlı; asıl faaliyet mağara otel ve taş ev restorasyonu. Bu projelerde mekânın oyulmuş dokusunu ve iç hacmini göstermek, klasik plandan çok daha etkili.",
 "emlak":"Mağara otel, taş konak ve bağ arazisi portföyün merkezinde; alıcının önemli kısmı yurt dışından. Çok dilli tanıtım videosu ve sanal tur, bu segmentte satışı kapatan adım.",
 "sanayi":"Turizm ve konaklama ilin ana ekonomisi; ayrıca Avanos çömlekçiliği, bağcılık-şarapçılık ve tarımsal işleme var. Şaraphane ve çömlek üreticileri için üretim süreci videosu, deneyim turizmini satmanın yolu.",
 "cografya":"Peribacaları, Göreme vadileri, Uçhisar Kalesi ve sabah balon manzarası; Türkiye'nin havadan çekimde dünyaca en tanınan coğrafyası.",
 "sektorler":["Turizm ve konaklama","Çömlekçilik","Bağcılık ve şarapçılık","Tarımsal işleme"],
 "komsu":["kayseri","aksaray","nigde","kirsehir"]},

{"slug":"nigde","ad":"Niğde","ek":"'de","icin":"'ye","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Bor","Çamardı","Ulukışla","Altunhisar"],
 "insaat":"Niğde'de konut üretimi merkez ve Bor hattında, üniversite ile sanayinin çektiği nüfusa dönük ilerliyor. Aladağlar çevresinde ise doğa turizmi amaçlı butik yatırım artıyor.",
 "emlak":"Merkez konut, elma bahçesi ve soğuk hava deposu portföyün kolları. Depo ve tarım tesisi satışında havadan ölçek gösterimi yatırımcı kararını hızlandırıyor.",
 "sanayi":"Elma üretimi ve soğuk hava depoculuğu Niğde'nin kimliği; ayrıca mermer, çimento ve gıda işleme güçlü. Meyve işleyicileri ve depo işletmecileri için süreç videosu, zincir market tedarik görüşmelerinde işe yarıyor.",
 "cografya":"Aladağlar'ın kayalık zirveleri, Kapadokya'ya uzanan vadiler ve Gümüşler Manastırı havadan çekimde sert ve yumuşak dokuyu bir arada veriyor.",
 "sektorler":["Elma ve soğuk hava depoculuğu","Mermer","Çimento","Gıda işleme","Dağ turizmi"],
 "komsu":["nevsehir","kayseri","adana","mersin"]},

{"slug":"ordu","ad":"Ordu","ek":"'da","icin":"'ya","ekip":"ortak","kademe":2,
 "ilceler":["Altınordu","Ünye","Fatsa","Perşembe","Gölköy","Kumru"],
 "insaat":"Ordu'da konut üretimi kıyı şeridinde yoğun ve dikey; dik yamaç nedeniyle deniz görüşü kat kat değişiyor. Bu farkı planda anlatmak mümkün olmadığı için 3D manzara simülasyonu satış ofisinin en işlevli aracı.",
 "emlak":"Deniz manzaralı daire, yayla evi ve fındık bahçesi portföyün üç kolu. Yurt dışında yaşayan hemşehri alıcı payı yüksek olduğundan sanal tur talebi belirgin.",
 "sanayi":"Fındık işleme Ordu'yu dünya pazarına bağlayan sektör; ayrıca balıkçılık, gıda ve turizm hizmetleri var. Fındık ihracatçıları için bahçe-kırma-paket süreci videosu, alıcıya izlenebilirliği tek seferde anlatıyor.",
 "cografya":"Boztepe'den görülen şehir ve liman, Çambaşı Yaylası, Perşembe Yaylası ve Yason Burnu havadan çekimde deniz-yayla geçişini güzel veriyor.",
 "sektorler":["Fındık işleme","Balıkçılık","Gıda","Yayla turizmi","Mobilya"],
 "komsu":["giresun","samsun","tokat","amasya"]},
]
