# -*- coding: utf-8 -*-
"""İl verisi — ek grup 2 (Çanakkale → Isparta)."""
EK = [
{"slug":"canakkale","ad":"Çanakkale","ek":"'de","icin":"'ye","ekip":"kendi","kademe":2,
 "ilceler":["Merkez","Ayvacık","Bozcaada","Gökçeada","Biga","Çan","Ezine","Küçükkuyu"],
 "insaat":"Çanakkale'de konut üretimi ikiye ayrılıyor: Assos-Küçükkuyu hattında butik yazlık projeleri, Biga ve Çan'da sanayi nüfusuna dönük konut. Kıyı projelerinde yapı yüksekliği kısıtlı olduğu için değer, manzara açısı ve peyzajda toplanıyor.",
 "emlak":"Bozcaada ve Gökçeada'da bağ evi ve taş ev, Assos'ta zeytinlik içinde villa portföyü var. Alıcının çoğu İstanbul ve Ankara'dan geldiği için mülkün uzaktan gezilebilmesi satışın önkoşulu.",
 "sanayi":"Seramik ve kaolen, gıda işleme, konservecilik ve balıkçılık öne çıkıyor; Çan'da termik enerji var. Seramik ve gıda üreticileri için üretim süreci videosu, zincir market ve ihracat görüşmelerinde güven kuruyor.",
 "cografya":"Truva, Assos'un denize bakan akropolü, Gelibolu Yarımadası ve Bozcaada'nın bağları havadan çekimde tarih ve deniz aynı karede buluşuyor.",
 "sektorler":["Seramik ve kaolen","Gıda ve konserve","Balıkçılık","Bağcılık ve şaraphane","Turizm"],
 "komsu":["balikesir","tekirdag","edirne","bursa"]},

{"slug":"cankiri","ad":"Çankırı","ek":"'da","icin":"'ya","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Çerkeş","Ilgaz","Şabanözü","Orta"],
 "insaat":"Çankırı'da konut üretimi düşük hacimli ama üniversite ve OSB'nin çektiği nüfus istikrarlı talep yaratıyor. Ilgaz çevresinde turizm amaçlı dağ evi yatırımı artıyor.",
 "emlak":"Merkez konut portföyünün yanında Ilgaz'da bungalov ve dağ evi hareketli. Kış turizmine dönük mülklerde tanıtım videosu kiralama dolulukları için belirleyici.",
 "sanayi":"Kaya tuzu üretimi Çankırı'yı ülke çapında tanıtan kalem; ayrıca çimento, gıda ve orman ürünleri var. Tuz madeninin ölçeğini gösteren havadan çekim ve galeri animasyonu, hem satış hem turizm materyali oluyor.",
 "cografya":"Tuz Mağarası'nın galerileri, Ilgaz Dağı'nın kar örtüsü ve geniş step manzarası havadan çekimde birbirinden farklı üç doku sunuyor.",
 "sektorler":["Kaya tuzu ve madencilik","Çimento","Gıda","Orman ürünleri","Kış turizmi"],
 "komsu":["ankara","kastamonu","corum","karabuk"]},

{"slug":"corum","ad":"Çorum","ek":"'da","icin":"'a","ekip":"ortak","kademe":2,
 "ilceler":["Merkez","Sungurlu","Osmancık","İskilip","Alaca","Bayat"],
 "insaat":"Çorum'da konut üretimi merkez çevresinde, sanayinin çektiği nüfusa dönük ilerliyor. Şehir kendi müteahhitleriyle büyüyen, dışa bağımlı olmayan bir yapı piyasasına sahip.",
 "emlak":"Merkez konut ve OSB çevresindeki sanayi parseli portföyün iki ana kolu. Fabrika ve depo satışlarında havadan ölçek gösterimi yatırımcı kararını hızlandırıyor.",
 "sanayi":"Makine imalatı, döküm, tuğla-kiremit ve gıda Çorum'un dört ayağı; leblebi ise şehrin markası. Makine üreticileri için çalışma prensibi animasyonu, ihracat pazarında tercümansız anlatım sağlıyor.",
 "cografya":"Hattuşa'nın antik surları, Boğazkale ve İncesu Kanyonu havadan çekimde 3500 yıllık bir katmanı görünür kılıyor.",
 "sektorler":["Makine imalatı ve döküm","Tuğla ve kiremit","Gıda (leblebi, un)","Değirmen makineleri"],
 "komsu":["amasya","yozgat","samsun","cankiri"]},

{"slug":"diyarbakir","ad":"Diyarbakır","ek":"'da","icin":"'a","ekip":"ortak","kademe":2,
 "ilceler":["Bağlar","Kayapınar","Yenişehir","Sur","Ergani","Bismil","Silvan"],
 "insaat":"Diyarbakır'da konut üretimi Kayapınar ve Bağlar hattında yoğun; genç nüfus ve hızlı kentleşme talebi sürekli canlı tutuyor. Sur'daki tarihi dokuda ise restorasyon ve yenileme projeleri ayrı bir anlatım gerektiriyor.",
 "emlak":"Yeni gelişen bölgelerde konut, çevre yolunda ticari mülk ve depo portföyü hareketli. Şehir dışında yaşayan alıcı payı yüksek olduğundan videolu ilan belirgin fark yaratıyor.",
 "sanayi":"Mermer, gıda işleme, tekstil ve inşaat malzemesi öne çıkıyor; ayrıca tarımsal üretim güçlü. Mermer üreticileri için damar ve plaka animasyonu, yurt dışı alıcıya numune öncesi karar verdiriyor.",
 "cografya":"5 kilometrelik siyah bazalt surlar, On Gözlü Köprü ve Hevsel Bahçeleri havadan çekimde UNESCO listesindeki bir siluet sunuyor.",
 "sektorler":["Mermer ve doğal taş","Gıda işleme","Tekstil","İnşaat malzemesi","Tarım"],
 "komsu":["batman","mardin","sanliurfa","elazig"]},

{"slug":"duzce","ad":"Düzce","ek":"'de","icin":"'ye","ekip":"kendi","kademe":2,
 "ilceler":["Merkez","Akçakoca","Kaynaşlı","Gölyaka","Yığılca"],
 "insaat":"Düzce'de konut üretimi hem yerel talebe hem de İstanbul'dan gelen ikinci konut talebine hizmet ediyor. Deprem sonrası yapı güvenliği vurgusu satış anlatımının merkezinde.",
 "emlak":"Akçakoca'da deniz manzaralı daire, Gölyaka çevresinde bungalov ve arazi portföyü öne çıkıyor. Bungalov işletmeciliğinde tanıtım videosu doluluğun ana belirleyicisi.",
 "sanayi":"Otomotiv yan sanayi, silah imalatı, orman ürünleri ve fındık işleme Düzce'nin üretim kolları. Otomotiv parça üreticileri için montaj ve dayanım animasyonu, ana sanayi görüşmelerinde teknik anlatımı kısaltıyor.",
 "cografya":"Akçakoca sahili, Samandere Şelalesi ve Efteni Gölü; ormanla denizin kısa mesafede buluştuğu, Bursa'dan aynı gün ulaşılabilen bir il.",
 "sektorler":["Otomotiv yan sanayi","Orman ürünleri","Fındık işleme","Silah imalatı","Turizm"],
 "komsu":["bolu","sakarya","zonguldak"]},

{"slug":"edirne","ad":"Edirne","ek":"'de","icin":"'ye","ekip":"ortak","kademe":2,
 "ilceler":["Merkez","Keşan","Uzunköprü","İpsala","Enez","Havsa"],
 "insaat":"Edirne'de konut üretimi merkez ve Keşan hattında; sınır ticareti ve üniversite nüfusu talebi besliyor. Enez ve Saros kıyısında ise yazlık proje yatırımı artıyor.",
 "emlak":"Saros Körfezi çevresinde yazlık ve arazi, merkezde ise tarihi doku içinde konut portföyü var. Bulgaristan ve Yunanistan sınırına yakınlık, ticari mülkte ayrı bir talep yaratıyor.",
 "sanayi":"Tarımsal işleme, çeltik ve un sanayi, süt ürünleri ve deri üretimi öne çıkıyor. Gıda üreticileri için hasat-işleme-paket videosu, Avrupa pazarına açılırken izlenebilirlik anlatımını kolaylaştırıyor.",
 "cografya":"Selimiye Camii'nin dört minareli silueti, Meriç ve Tunca köprüleri, Saros'un uzun kumsalı havadan çekimde güçlü açılış planları veriyor.",
 "sektorler":["Tarımsal işleme ve un","Süt ürünleri","Deri","Sınır ticareti","Turizm"],
 "komsu":["tekirdag","kirklareli","canakkale"]},

{"slug":"elazig","ad":"Elazığ","ek":"'da","icin":"'a","ekip":"ortak","kademe":2,
 "ilceler":["Merkez","Kovancılar","Karakoçan","Palu","Maden","Sivrice"],
 "insaat":"Elazığ'da konut üretimi deprem sonrası güçlendirilmiş yapı standardı üzerinden anlatılıyor; merkez çevresinde yeni siteler yükseliyor. Hazar Gölü kıyısında ise turizm amaçlı proje yatırımı var.",
 "emlak":"Merkez konut portföyünün yanında Sivrice ve Hazar Gölü çevresinde yazlık ve arazi hareketli. Göl manzaralı mülkte manzaranın hangi kattan göründüğü satışın belirleyicisi.",
 "sanayi":"Krom ve bakır madenciliği, çimento, gıda işleme ve mermer öne çıkıyor; Harput üzüm ve şarapçılığı da canlı. Maden ve çimento tesislerinde havadan ölçek çekimi, yatırımcı sunumunun ana materyali.",
 "cografya":"Hazar Gölü'nün turkuaz suyu, Harput Kalesi'nin şehre bakan yamacı ve Keban Barajı havadan çekimde geniş açı için ideal.",
 "sektorler":["Madencilik (krom, bakır)","Çimento","Mermer","Gıda ve bağcılık","Enerji"],
 "komsu":["malatya","diyarbakir","bingol","tunceli"]},

{"slug":"erzincan","ad":"Erzincan","ek":"'da","icin":"'a","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Refahiye","Tercan","Üzümlü","Kemaliye"],
 "insaat":"Erzincan'da konut üretimi geniş ova sayesinde yatay ve planlı ilerliyor; deprem yönetmeliği vurgusu satışın ilk konusu. Kemaliye'de ise tarihi taş ev restorasyonu ayrı bir alan.",
 "emlak":"Merkez konut ve ova arazisi portföyün büyük kısmı; Kemaliye'de turizm amaçlı taş ev talebi artıyor. Arazi ilanlarında sulama ve yol bağlantısının havadan gösterilmesi belirleyici.",
 "sanayi":"Bakır madenciliği, tulum peyniri ve süt ürünleri, bakırcılık ve gıda işleme öne çıkıyor. Peynir üreticileri için üretim ve olgunlaştırma videosu, coğrafi işaretli ürünün değerini görünür kılıyor.",
 "cografya":"Karanlık Kanyon'un dar duvarları, Kemaliye'nin Taşyolu ve geniş Erzincan ovası havadan çekimde uç noktada iki farklı ölçek sunuyor.",
 "sektorler":["Madencilik","Süt ürünleri ve peynircilik","Bakırcılık","Gıda işleme","Doğa turizmi"],
 "komsu":["erzurum","tunceli","gumushane","sivas"]},

{"slug":"erzurum","ad":"Erzurum","ek":"'da","icin":"'a","ekip":"ortak","kademe":2,
 "ilceler":["Yakutiye","Palandöken","Aziziye","Oltu","Horasan","İspir"],
 "insaat":"Erzurum'da konut üretimi Palandöken hattında kayak turizmine dönük projelerle şehir içi konut arasında bölünüyor. Sert iklim nedeniyle yalıtım ve ısıtma performansı satış argümanının merkezinde.",
 "emlak":"Kayak merkezine yakın daire ve otel yatırımı ilin en değerli portföyü. Sezonluk kiralama yapan mülklerde tanıtım videosu doluluğu doğrudan etkiliyor.",
 "sanayi":"Hayvancılık ve süt ürünleri, oltu taşı işlemeciliği, gıda ve turizm hizmetleri öne çıkıyor. Oltu taşı üreticileri için ürün 3D vitrini, küçük ama yüksek katma değerli ürünü online satmayı kolaylaştırıyor.",
 "cografya":"Palandöken'in uzun pistleri, Çifte Minareli Medrese, Tortum Şelalesi ve geniş yayla; kışın havadan çekim için Türkiye'nin en güçlü kar manzaralarından biri.",
 "sektorler":["Kış turizmi ve konaklama","Hayvancılık ve süt ürünleri","Oltu taşı","Gıda işleme"],
 "komsu":["erzincan","kars","agri","bayburt"]},

{"slug":"giresun","ad":"Giresun","ek":"'da","icin":"'a","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Bulancak","Espiye","Tirebolu","Görele","Şebinkarahisar"],
 "insaat":"Giresun'da dar kıyı şeridi ve dik yamaç, konut projelerini yatay değil dikey büyümeye zorluyor. Hangi dairenin denizi gördüğü kotlar arası farktan dolayı planda anlaşılmadığı için modelleme değerli.",
 "emlak":"Deniz manzaralı daire, yayla evi ve fındık bahçesi portföyün üç kolu. Yayla evlerinde ve fındıklıklarda havadan sınır gösterimi alıcının ilk sorusunu kapatıyor.",
 "sanayi":"Fındık işleme Giresun'un dünya çapındaki kimliği; ayrıca balıkçılık, gıda ve orman ürünleri var. Fındık ihracatçıları için bahçeden pakete uzanan süreç videosu, izlenebilirlik anlatımını tek karede veriyor.",
 "cografya":"Giresun Adası, Kümbet ve Kulakkaya yaylaları, Tirebolu kıyısı; deniz ile yaylanın yarım saat mesafede olduğu ender illerden.",
 "sektorler":["Fındık işleme","Balıkçılık","Orman ürünleri","Yayla turizmi","Gıda"],
 "komsu":["ordu","trabzon","gumushane","sivas"]},

{"slug":"gumushane","ad":"Gümüşhane","ek":"'de","icin":"'ye","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Kelkit","Şiran","Torul","Kürtün"],
 "insaat":"Gümüşhane'de konut üretimi sınırlı; asıl hareket turizm amaçlı bungalov ve dağ evi yatırımlarında. Vadi içine kurulan yapılarda arazi eğimi ve manzara açısı projenin tamamını belirliyor.",
 "emlak":"Yayla evi, vadi arazisi ve merkez konut portföyün kolları. Şehir dışında yaşayan hemşehri alıcı ağırlıkta olduğu için uzaktan gezilebilir ilan avantaj sağlıyor.",
 "sanayi":"Madencilik, pestil-köme üretimi, süt ürünleri ve orman ürünleri öne çıkıyor. Pestil ve köme üreticileri için üretim süreci videosu, hediyelik gıda pazarında markalaşmayı hızlandırıyor.",
 "cografya":"Karaca Mağarası'nın sarkıtları, Tomara Şelalesi, Zigana geçidi ve Süleymaniye'nin taş evleri havadan çekimde derinlik veriyor.",
 "sektorler":["Madencilik","Pestil ve köme üretimi","Süt ürünleri","Orman ürünleri","Doğa turizmi"],
 "komsu":["trabzon","bayburt","erzincan","giresun"]},

{"slug":"hakkari","ad":"Hakkâri","ek":"'de","icin":"'ye","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Yüksekova","Şemdinli","Çukurca","Derecik"],
 "insaat":"Hakkâri'de konut üretimi ağırlıklı olarak kamu yatırımı ve TOKİ eliyle ilerliyor; Yüksekova'da özel sektör projeleri artıyor. Dik topografya nedeniyle yerleşim planı ancak 3D modelde anlaşılıyor.",
 "emlak":"Yüksekova'da ticari mülk ve konut, merkezde ise sınırlı konut portföyü var. Sınır ticareti nedeniyle depo ve ticari alan talebi konuttan daha hareketli.",
 "sanayi":"Hayvancılık, bal üretimi ve sınır ticareti lojistiği ilin ekonomik kolları. Bal üreticileri için yayla ve hasat videosu, yüksek rakım balının değerini anlatmanın en doğrudan yolu.",
 "cografya":"Cilo-Sat buzul dağları, Yüksekova ovası ve derin vadiler; Türkiye'nin havadan çekimde en az görüntülenmiş, en dramatik coğrafyalarından biri.",
 "sektorler":["Hayvancılık","Arıcılık ve bal","Sınır ticareti","Dağ turizmi"],
 "komsu":["van","sirnak","siirt"]},

{"slug":"hatay","ad":"Hatay","ek":"'da","icin":"'a","ekip":"ortak","kademe":2,
 "ilceler":["Antakya","İskenderun","Defne","Samandağ","Dörtyol","Arsuz","Belen"],
 "insaat":"Hatay'da inşaatın gündemi deprem sonrası yeniden inşa; Antakya ve İskenderun'da büyük ölçekli yeni yerleşimler kuruluyor. Hak sahibine ve alıcıya yapının ne olacağını göstermek, bu ilde görselleştirmenin en kritik kullanım alanı.",
 "emlak":"Yeni teslim konutlar, Arsuz ve Samandağ'da sahil mülkü, İskenderun'da ticari alan portföyün ana kalemleri. Şehir dışına taşınmış alıcı payı yüksek olduğu için uzaktan gezilebilir ilan zorunlu hale geldi.",
 "sanayi":"Demir-çelik İskenderun hattında ülke ölçeğinde; ayrıca liman lojistiği, gıda ve zeytinyağı güçlü. Ağır sanayi tesislerinde 3D animasyon, gizlilik gerektiren üretim sürecini anlatmanın güvenli yolu.",
 "cografya":"Amanos Dağları'nın denize inişi, Samandağ kumsalı, Titus Tüneli ve Antakya'nın yeniden kurulan dokusu havadan çekimde güçlü bir hikâye anlatıyor.",
 "sektorler":["Demir-çelik","Liman ve lojistik","Gıda ve zeytinyağı","Tarım","Turizm ve gastronomi"],
 "komsu":["adana","osmaniye","gaziantep","kilis"]},

{"slug":"igdir","ad":"Iğdır","ek":"'da","icin":"'a","ekip":"ortak","kademe":3,
 "ilceler":["Merkez","Tuzluca","Aralık","Karakoyunlu"],
 "insaat":"Iğdır'da konut üretimi merkez çevresinde, sınır ticaretinin beslediği nüfusa dönük ilerliyor. Ova ikliminin avantajı proje anlatımında sıkça kullanılıyor.",
 "emlak":"Tarım arazisi ve meyve bahçesi portföyün en hareketli kalemi; merkezde konut talebi istikrarlı. Arazi satışında sulama altyapısının ve parsel sınırının havadan gösterilmesi kararı hızlandırıyor.",
 "sanayi":"Kayısı ve meyve işleme, pamuk, hayvancılık ve sınır ticareti lojistiği öne çıkıyor. Meyve işleyicileri için bahçeden pakete süreç videosu, ihracat müşterisine izlenebilirlik anlatıyor.",
 "cografya":"Ağrı Dağı'nın Iğdır ovasından görünen dev silueti ve Aras Nehri havadan çekimde ölçek duygusu güçlü kareler veriyor.",
 "sektorler":["Meyve işleme (kayısı)","Pamuk ve tarım","Hayvancılık","Sınır ticareti"],
 "komsu":["agri","kars","van"]},

{"slug":"isparta","ad":"Isparta","ek":"'da","icin":"'ya","ekip":"ortak","kademe":2,
 "ilceler":["Merkez","Eğirdir","Yalvaç","Şarkikaraağaç","Gelendost","Sütçüler"],
 "insaat":"Isparta'da konut talebini üniversite nüfusu ve Eğirdir çevresindeki turizm yatırımları belirliyor. Göl manzaralı projelerde manzara açısının doğru gösterilmesi fiyat farkını doğrudan etkiliyor.",
 "emlak":"Eğirdir Gölü kıyısında yazlık ve pansiyon, merkezde öğrenciye dönük konut portföyü var. Turizm mülkünde tanıtım videosu sezonluk doluluğu belirliyor.",
 "sanayi":"Gül ve gülyağı üretimi Isparta'yı dünya pazarına bağlıyor; ayrıca halı-kilim, elma ve orman ürünleri güçlü. Gülyağı ve kozmetik üreticileri için hasattan damıtmaya uzanan süreç videosu, premium fiyatı meşrulaştıran anlatım.",
 "cografya":"Eğirdir Gölü'nün yarımadası, Kovada Milli Parkı, gül tarlaları ve Davraz'ın kar örtüsü havadan çekimde mevsime göre bambaşka görüntüler veriyor.",
 "sektorler":["Gül ve gülyağı","Halı ve kilim","Elma ve tarım","Orman ürünleri","Turizm"],
 "komsu":["burdur","antalya","konya","afyonkarahisar"]},
]
